//
// Copyright (C) 2021 Grakn Labs
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: v2/protobuf/cluster/database.proto

package grakn_protocol_cluster

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Database struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Replicas []*Database_Replica `protobuf:"bytes,2,rep,name=replicas,proto3" json:"replicas,omitempty"`
}

func (x *Database) Reset() {
	*x = Database{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_cluster_database_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_cluster_database_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_cluster_database_proto_rawDescGZIP(), []int{0}
}

func (x *Database) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Database) GetReplicas() []*Database_Replica {
	if x != nil {
		return x.Replicas
	}
	return nil
}

type Database_Replica struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address            string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Primary            bool   `protobuf:"varint,2,opt,name=primary,proto3" json:"primary,omitempty"`
	PreferredSecondary bool   `protobuf:"varint,3,opt,name=preferred_secondary,json=preferredSecondary,proto3" json:"preferred_secondary,omitempty"`
	Term               int64  `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
}

func (x *Database_Replica) Reset() {
	*x = Database_Replica{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_cluster_database_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Database_Replica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database_Replica) ProtoMessage() {}

func (x *Database_Replica) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_cluster_database_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database_Replica.ProtoReflect.Descriptor instead.
func (*Database_Replica) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_cluster_database_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Database_Replica) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Database_Replica) GetPrimary() bool {
	if x != nil {
		return x.Primary
	}
	return false
}

func (x *Database_Replica) GetPreferredSecondary() bool {
	if x != nil {
		return x.PreferredSecondary
	}
	return false
}

func (x *Database_Replica) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type Database_Get struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Database_Get) Reset() {
	*x = Database_Get{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_cluster_database_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Database_Get) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database_Get) ProtoMessage() {}

func (x *Database_Get) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_cluster_database_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database_Get.ProtoReflect.Descriptor instead.
func (*Database_Get) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_cluster_database_proto_rawDescGZIP(), []int{0, 1}
}

type Database_All struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Database_All) Reset() {
	*x = Database_All{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_cluster_database_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Database_All) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database_All) ProtoMessage() {}

func (x *Database_All) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_cluster_database_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database_All.ProtoReflect.Descriptor instead.
func (*Database_All) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_cluster_database_proto_rawDescGZIP(), []int{0, 2}
}

type Database_Get_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Database_Get_Req) Reset() {
	*x = Database_Get_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_cluster_database_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Database_Get_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database_Get_Req) ProtoMessage() {}

func (x *Database_Get_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_cluster_database_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database_Get_Req.ProtoReflect.Descriptor instead.
func (*Database_Get_Req) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_cluster_database_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *Database_Get_Req) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Database_Get_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Database *Database `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
}

func (x *Database_Get_Res) Reset() {
	*x = Database_Get_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_cluster_database_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Database_Get_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database_Get_Res) ProtoMessage() {}

func (x *Database_Get_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_cluster_database_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database_Get_Res.ProtoReflect.Descriptor instead.
func (*Database_Get_Res) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_cluster_database_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *Database_Get_Res) GetDatabase() *Database {
	if x != nil {
		return x.Database
	}
	return nil
}

type Database_All_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Database_All_Req) Reset() {
	*x = Database_All_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_cluster_database_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Database_All_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database_All_Req) ProtoMessage() {}

func (x *Database_All_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_cluster_database_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database_All_Req.ProtoReflect.Descriptor instead.
func (*Database_All_Req) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_cluster_database_proto_rawDescGZIP(), []int{0, 2, 0}
}

type Database_All_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Databases []*Database `protobuf:"bytes,1,rep,name=databases,proto3" json:"databases,omitempty"`
}

func (x *Database_All_Res) Reset() {
	*x = Database_All_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_cluster_database_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Database_All_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database_All_Res) ProtoMessage() {}

func (x *Database_All_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_cluster_database_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database_All_Res.ProtoReflect.Descriptor instead.
func (*Database_All_Res) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_cluster_database_proto_rawDescGZIP(), []int{0, 2, 1}
}

func (x *Database_All_Res) GetDatabases() []*Database {
	if x != nil {
		return x.Databases
	}
	return nil
}

var File_v2_protobuf_cluster_database_proto protoreflect.FileDescriptor

var file_v2_protobuf_cluster_database_proto_rawDesc = []byte{
	0x0a, 0x22, 0x76, 0x32, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x22, 0xa5, 0x03, 0x0a,
	0x08, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x44, 0x0a,
	0x08, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x28, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x73, 0x1a, 0x82, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x69,
	0x6d, 0x61, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x69, 0x6d,
	0x61, 0x72, 0x79, 0x12, 0x2f, 0x0a, 0x13, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64,
	0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x12, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x53, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x61, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x1a, 0x65, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x1a,
	0x19, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x43, 0x0a, 0x03, 0x52, 0x65,
	0x73, 0x12, 0x3c, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x62, 0x61, 0x73, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x1a,
	0x53, 0x0a, 0x03, 0x41, 0x6c, 0x6c, 0x1a, 0x05, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x1a, 0x45, 0x0a,
	0x03, 0x52, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x73, 0x42, 0x5b, 0x0a, 0x16, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x42, 0x0d,
	0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x32, 0x2e,
	0x2f, 0x76, 0x32, 0x2f, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x5f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x3b, 0x67, 0x72, 0x61, 0x6b, 0x6e,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v2_protobuf_cluster_database_proto_rawDescOnce sync.Once
	file_v2_protobuf_cluster_database_proto_rawDescData = file_v2_protobuf_cluster_database_proto_rawDesc
)

func file_v2_protobuf_cluster_database_proto_rawDescGZIP() []byte {
	file_v2_protobuf_cluster_database_proto_rawDescOnce.Do(func() {
		file_v2_protobuf_cluster_database_proto_rawDescData = protoimpl.X.CompressGZIP(file_v2_protobuf_cluster_database_proto_rawDescData)
	})
	return file_v2_protobuf_cluster_database_proto_rawDescData
}

var file_v2_protobuf_cluster_database_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v2_protobuf_cluster_database_proto_goTypes = []interface{}{
	(*Database)(nil),         // 0: grakn.protocol.cluster.Database
	(*Database_Replica)(nil), // 1: grakn.protocol.cluster.Database.Replica
	(*Database_Get)(nil),     // 2: grakn.protocol.cluster.Database.Get
	(*Database_All)(nil),     // 3: grakn.protocol.cluster.Database.All
	(*Database_Get_Req)(nil), // 4: grakn.protocol.cluster.Database.Get.Req
	(*Database_Get_Res)(nil), // 5: grakn.protocol.cluster.Database.Get.Res
	(*Database_All_Req)(nil), // 6: grakn.protocol.cluster.Database.All.Req
	(*Database_All_Res)(nil), // 7: grakn.protocol.cluster.Database.All.Res
}
var file_v2_protobuf_cluster_database_proto_depIdxs = []int32{
	1, // 0: grakn.protocol.cluster.Database.replicas:type_name -> grakn.protocol.cluster.Database.Replica
	0, // 1: grakn.protocol.cluster.Database.Get.Res.database:type_name -> grakn.protocol.cluster.Database
	0, // 2: grakn.protocol.cluster.Database.All.Res.databases:type_name -> grakn.protocol.cluster.Database
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v2_protobuf_cluster_database_proto_init() }
func file_v2_protobuf_cluster_database_proto_init() {
	if File_v2_protobuf_cluster_database_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v2_protobuf_cluster_database_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Database); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_cluster_database_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Database_Replica); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_cluster_database_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Database_Get); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_cluster_database_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Database_All); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_cluster_database_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Database_Get_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_cluster_database_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Database_Get_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_cluster_database_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Database_All_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_cluster_database_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Database_All_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v2_protobuf_cluster_database_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_protobuf_cluster_database_proto_goTypes,
		DependencyIndexes: file_v2_protobuf_cluster_database_proto_depIdxs,
		MessageInfos:      file_v2_protobuf_cluster_database_proto_msgTypes,
	}.Build()
	File_v2_protobuf_cluster_database_proto = out.File
	file_v2_protobuf_cluster_database_proto_rawDesc = nil
	file_v2_protobuf_cluster_database_proto_goTypes = nil
	file_v2_protobuf_cluster_database_proto_depIdxs = nil
}
