// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: v1/protobuf/console.proto

package grakn_protocol

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type UserManagement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserManagement) Reset() {
	*x = UserManagement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_protobuf_console_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserManagement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserManagement) ProtoMessage() {}

func (x *UserManagement) ProtoReflect() protoreflect.Message {
	mi := &file_v1_protobuf_console_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserManagement.ProtoReflect.Descriptor instead.
func (*UserManagement) Descriptor() ([]byte, []int) {
	return file_v1_protobuf_console_proto_rawDescGZIP(), []int{0}
}

type Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Login) Reset() {
	*x = Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_protobuf_console_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login) ProtoMessage() {}

func (x *Login) ProtoReflect() protoreflect.Message {
	mi := &file_v1_protobuf_console_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login.ProtoReflect.Descriptor instead.
func (*Login) Descriptor() ([]byte, []int) {
	return file_v1_protobuf_console_proto_rawDescGZIP(), []int{1}
}

type Create struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Create) Reset() {
	*x = Create{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_protobuf_console_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Create) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create) ProtoMessage() {}

func (x *Create) ProtoReflect() protoreflect.Message {
	mi := &file_v1_protobuf_console_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create.ProtoReflect.Descriptor instead.
func (*Create) Descriptor() ([]byte, []int) {
	return file_v1_protobuf_console_proto_rawDescGZIP(), []int{2}
}

type Delete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Delete) Reset() {
	*x = Delete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_protobuf_console_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delete) ProtoMessage() {}

func (x *Delete) ProtoReflect() protoreflect.Message {
	mi := &file_v1_protobuf_console_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delete.ProtoReflect.Descriptor instead.
func (*Delete) Descriptor() ([]byte, []int) {
	return file_v1_protobuf_console_proto_rawDescGZIP(), []int{3}
}

type Retrieve struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Retrieve) Reset() {
	*x = Retrieve{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_protobuf_console_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Retrieve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Retrieve) ProtoMessage() {}

func (x *Retrieve) ProtoReflect() protoreflect.Message {
	mi := &file_v1_protobuf_console_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Retrieve.ProtoReflect.Descriptor instead.
func (*Retrieve) Descriptor() ([]byte, []int) {
	return file_v1_protobuf_console_proto_rawDescGZIP(), []int{4}
}

type RetrieveAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RetrieveAll) Reset() {
	*x = RetrieveAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_protobuf_console_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveAll) ProtoMessage() {}

func (x *RetrieveAll) ProtoReflect() protoreflect.Message {
	mi := &file_v1_protobuf_console_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveAll.ProtoReflect.Descriptor instead.
func (*RetrieveAll) Descriptor() ([]byte, []int) {
	return file_v1_protobuf_console_proto_rawDescGZIP(), []int{5}
}

type Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Update) Reset() {
	*x = Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_protobuf_console_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_v1_protobuf_console_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_v1_protobuf_console_proto_rawDescGZIP(), []int{6}
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Role     string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_protobuf_console_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_v1_protobuf_console_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_v1_protobuf_console_proto_rawDescGZIP(), []int{7}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UserManagement_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Req:
	//	*UserManagement_Req_LoginReq
	//	*UserManagement_Req_CreateReq
	//	*UserManagement_Req_DeleteReq
	//	*UserManagement_Req_RetrieveReq
	//	*UserManagement_Req_RetrieveAllReq
	//	*UserManagement_Req_UpdateReq
	Req isUserManagement_Req_Req `protobuf_oneof:"req"`
}

func (x *UserManagement_Req) Reset() {
	*x = UserManagement_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_protobuf_console_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserManagement_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserManagement_Req) ProtoMessage() {}

func (x *UserManagement_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v1_protobuf_console_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserManagement_Req.ProtoReflect.Descriptor instead.
func (*UserManagement_Req) Descriptor() ([]byte, []int) {
	return file_v1_protobuf_console_proto_rawDescGZIP(), []int{0, 0}
}

func (m *UserManagement_Req) GetReq() isUserManagement_Req_Req {
	if m != nil {
		return m.Req
	}
	return nil
}

func (x *UserManagement_Req) GetLoginReq() *Login_Req {
	if x, ok := x.GetReq().(*UserManagement_Req_LoginReq); ok {
		return x.LoginReq
	}
	return nil
}

func (x *UserManagement_Req) GetCreateReq() *Create_Req {
	if x, ok := x.GetReq().(*UserManagement_Req_CreateReq); ok {
		return x.CreateReq
	}
	return nil
}

func (x *UserManagement_Req) GetDeleteReq() *Delete_Req {
	if x, ok := x.GetReq().(*UserManagement_Req_DeleteReq); ok {
		return x.DeleteReq
	}
	return nil
}

func (x *UserManagement_Req) GetRetrieveReq() *Retrieve_Req {
	if x, ok := x.GetReq().(*UserManagement_Req_RetrieveReq); ok {
		return x.RetrieveReq
	}
	return nil
}

func (x *UserManagement_Req) GetRetrieveAllReq() *RetrieveAll_Req {
	if x, ok := x.GetReq().(*UserManagement_Req_RetrieveAllReq); ok {
		return x.RetrieveAllReq
	}
	return nil
}

func (x *UserManagement_Req) GetUpdateReq() *Update_Req {
	if x, ok := x.GetReq().(*UserManagement_Req_UpdateReq); ok {
		return x.UpdateReq
	}
	return nil
}

type isUserManagement_Req_Req interface {
	isUserManagement_Req_Req()
}

type UserManagement_Req_LoginReq struct {
	LoginReq *Login_Req `protobuf:"bytes,1,opt,name=login_req,json=loginReq,proto3,oneof"`
}

type UserManagement_Req_CreateReq struct {
	CreateReq *Create_Req `protobuf:"bytes,2,opt,name=create_req,json=createReq,proto3,oneof"`
}

type UserManagement_Req_DeleteReq struct {
	DeleteReq *Delete_Req `protobuf:"bytes,3,opt,name=delete_req,json=deleteReq,proto3,oneof"`
}

type UserManagement_Req_RetrieveReq struct {
	RetrieveReq *Retrieve_Req `protobuf:"bytes,4,opt,name=retrieve_req,json=retrieveReq,proto3,oneof"`
}

type UserManagement_Req_RetrieveAllReq struct {
	RetrieveAllReq *RetrieveAll_Req `protobuf:"bytes,5,opt,name=retrieve_all_req,json=retrieveAllReq,proto3,oneof"`
}

type UserManagement_Req_UpdateReq struct {
	UpdateReq *Update_Req `protobuf:"bytes,6,opt,name=update_req,json=updateReq,proto3,oneof"`
}

func (*UserManagement_Req_LoginReq) isUserManagement_Req_Req() {}

func (*UserManagement_Req_CreateReq) isUserManagement_Req_Req() {}

func (*UserManagement_Req_DeleteReq) isUserManagement_Req_Req() {}

func (*UserManagement_Req_RetrieveReq) isUserManagement_Req_Req() {}

func (*UserManagement_Req_RetrieveAllReq) isUserManagement_Req_Req() {}

func (*UserManagement_Req_UpdateReq) isUserManagement_Req_Req() {}

type UserManagement_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Res:
	//	*UserManagement_Res_LoginRes
	//	*UserManagement_Res_CreateRes
	//	*UserManagement_Res_DeleteRes
	//	*UserManagement_Res_RetrieveRes
	//	*UserManagement_Res_RetrieveAllRes
	//	*UserManagement_Res_UpdateRes
	Res isUserManagement_Res_Res `protobuf_oneof:"res"`
}

func (x *UserManagement_Res) Reset() {
	*x = UserManagement_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_protobuf_console_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserManagement_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserManagement_Res) ProtoMessage() {}

func (x *UserManagement_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v1_protobuf_console_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserManagement_Res.ProtoReflect.Descriptor instead.
func (*UserManagement_Res) Descriptor() ([]byte, []int) {
	return file_v1_protobuf_console_proto_rawDescGZIP(), []int{0, 1}
}

func (m *UserManagement_Res) GetRes() isUserManagement_Res_Res {
	if m != nil {
		return m.Res
	}
	return nil
}

func (x *UserManagement_Res) GetLoginRes() *Login_Res {
	if x, ok := x.GetRes().(*UserManagement_Res_LoginRes); ok {
		return x.LoginRes
	}
	return nil
}

func (x *UserManagement_Res) GetCreateRes() *Create_Res {
	if x, ok := x.GetRes().(*UserManagement_Res_CreateRes); ok {
		return x.CreateRes
	}
	return nil
}

func (x *UserManagement_Res) GetDeleteRes() *Delete_Res {
	if x, ok := x.GetRes().(*UserManagement_Res_DeleteRes); ok {
		return x.DeleteRes
	}
	return nil
}

func (x *UserManagement_Res) GetRetrieveRes() *Retrieve_Res {
	if x, ok := x.GetRes().(*UserManagement_Res_RetrieveRes); ok {
		return x.RetrieveRes
	}
	return nil
}

func (x *UserManagement_Res) GetRetrieveAllRes() *RetrieveAll_Res {
	if x, ok := x.GetRes().(*UserManagement_Res_RetrieveAllRes); ok {
		return x.RetrieveAllRes
	}
	return nil
}

func (x *UserManagement_Res) GetUpdateRes() *Update_Res {
	if x, ok := x.GetRes().(*UserManagement_Res_UpdateRes); ok {
		return x.UpdateRes
	}
	return nil
}

type isUserManagement_Res_Res interface {
	isUserManagement_Res_Res()
}

type UserManagement_Res_LoginRes struct {
	LoginRes *Login_Res `protobuf:"bytes,1,opt,name=login_res,json=loginRes,proto3,oneof"`
}

type UserManagement_Res_CreateRes struct {
	CreateRes *Create_Res `protobuf:"bytes,2,opt,name=create_res,json=createRes,proto3,oneof"`
}

type UserManagement_Res_DeleteRes struct {
	DeleteRes *Delete_Res `protobuf:"bytes,3,opt,name=delete_res,json=deleteRes,proto3,oneof"`
}

type UserManagement_Res_RetrieveRes struct {
	RetrieveRes *Retrieve_Res `protobuf:"bytes,4,opt,name=retrieve_res,json=retrieveRes,proto3,oneof"`
}

type UserManagement_Res_RetrieveAllRes struct {
	RetrieveAllRes *RetrieveAll_Res `protobuf:"bytes,5,opt,name=retrieve_all_res,json=retrieveAllRes,proto3,oneof"`
}

type UserManagement_Res_UpdateRes struct {
	UpdateRes *Update_Res `protobuf:"bytes,6,opt,name=update_res,json=updateRes,proto3,oneof"`
}

func (*UserManagement_Res_LoginRes) isUserManagement_Res_Res() {}

func (*UserManagement_Res_CreateRes) isUserManagement_Res_Res() {}

func (*UserManagement_Res_DeleteRes) isUserManagement_Res_Res() {}

func (*UserManagement_Res_RetrieveRes) isUserManagement_Res_Res() {}

func (*UserManagement_Res_RetrieveAllRes) isUserManagement_Res_Res() {}

func (*UserManagement_Res_UpdateRes) isUserManagement_Res_Res() {}

type Login_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *Login_Req) Reset() {
	*x = Login_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_protobuf_console_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login_Req) ProtoMessage() {}

func (x *Login_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v1_protobuf_console_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login_Req.ProtoReflect.Descriptor instead.
func (*Login_Req) Descriptor() ([]byte, []int) {
	return file_v1_protobuf_console_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Login_Req) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Login_Req) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Login_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Login_Res) Reset() {
	*x = Login_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_protobuf_console_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login_Res) ProtoMessage() {}

func (x *Login_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v1_protobuf_console_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login_Res.ProtoReflect.Descriptor instead.
func (*Login_Res) Descriptor() ([]byte, []int) {
	return file_v1_protobuf_console_proto_rawDescGZIP(), []int{1, 1}
}

type Create_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Role     string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *Create_Req) Reset() {
	*x = Create_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_protobuf_console_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Create_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create_Req) ProtoMessage() {}

func (x *Create_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v1_protobuf_console_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create_Req.ProtoReflect.Descriptor instead.
func (*Create_Req) Descriptor() ([]byte, []int) {
	return file_v1_protobuf_console_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Create_Req) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Create_Req) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Create_Req) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type Create_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *Create_Res) Reset() {
	*x = Create_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_protobuf_console_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Create_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create_Res) ProtoMessage() {}

func (x *Create_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v1_protobuf_console_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create_Res.ProtoReflect.Descriptor instead.
func (*Create_Res) Descriptor() ([]byte, []int) {
	return file_v1_protobuf_console_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Create_Res) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type Delete_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *Delete_Req) Reset() {
	*x = Delete_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_protobuf_console_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delete_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delete_Req) ProtoMessage() {}

func (x *Delete_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v1_protobuf_console_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delete_Req.ProtoReflect.Descriptor instead.
func (*Delete_Req) Descriptor() ([]byte, []int) {
	return file_v1_protobuf_console_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Delete_Req) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Delete_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *Delete_Res) Reset() {
	*x = Delete_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_protobuf_console_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delete_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delete_Res) ProtoMessage() {}

func (x *Delete_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v1_protobuf_console_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delete_Res.ProtoReflect.Descriptor instead.
func (*Delete_Res) Descriptor() ([]byte, []int) {
	return file_v1_protobuf_console_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Delete_Res) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Retrieve_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *Retrieve_Req) Reset() {
	*x = Retrieve_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_protobuf_console_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Retrieve_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Retrieve_Req) ProtoMessage() {}

func (x *Retrieve_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v1_protobuf_console_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Retrieve_Req.ProtoReflect.Descriptor instead.
func (*Retrieve_Req) Descriptor() ([]byte, []int) {
	return file_v1_protobuf_console_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Retrieve_Req) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Retrieve_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *Retrieve_Res) Reset() {
	*x = Retrieve_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_protobuf_console_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Retrieve_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Retrieve_Res) ProtoMessage() {}

func (x *Retrieve_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v1_protobuf_console_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Retrieve_Res.ProtoReflect.Descriptor instead.
func (*Retrieve_Res) Descriptor() ([]byte, []int) {
	return file_v1_protobuf_console_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Retrieve_Res) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type RetrieveAll_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RetrieveAll_Req) Reset() {
	*x = RetrieveAll_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_protobuf_console_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveAll_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveAll_Req) ProtoMessage() {}

func (x *RetrieveAll_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v1_protobuf_console_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveAll_Req.ProtoReflect.Descriptor instead.
func (*RetrieveAll_Req) Descriptor() ([]byte, []int) {
	return file_v1_protobuf_console_proto_rawDescGZIP(), []int{5, 0}
}

type RetrieveAll_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *RetrieveAll_Res) Reset() {
	*x = RetrieveAll_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_protobuf_console_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveAll_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveAll_Res) ProtoMessage() {}

func (x *RetrieveAll_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v1_protobuf_console_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveAll_Res.ProtoReflect.Descriptor instead.
func (*RetrieveAll_Res) Descriptor() ([]byte, []int) {
	return file_v1_protobuf_console_proto_rawDescGZIP(), []int{5, 1}
}

func (x *RetrieveAll_Res) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type Update_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Role     string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *Update_Req) Reset() {
	*x = Update_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_protobuf_console_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Update_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update_Req) ProtoMessage() {}

func (x *Update_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v1_protobuf_console_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update_Req.ProtoReflect.Descriptor instead.
func (*Update_Req) Descriptor() ([]byte, []int) {
	return file_v1_protobuf_console_proto_rawDescGZIP(), []int{6, 0}
}

func (x *Update_Req) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Update_Req) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Update_Req) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type Update_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *Update_Res) Reset() {
	*x = Update_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_protobuf_console_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Update_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update_Res) ProtoMessage() {}

func (x *Update_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v1_protobuf_console_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update_Res.ProtoReflect.Descriptor instead.
func (*Update_Res) Descriptor() ([]byte, []int) {
	return file_v1_protobuf_console_proto_rawDescGZIP(), []int{6, 1}
}

func (x *Update_Res) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_v1_protobuf_console_proto protoreflect.FileDescriptor

var file_v1_protobuf_console_proto_rawDesc = []byte{
	0x0a, 0x19, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x6f,
	0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfc, 0x04, 0x0a, 0x0e,
	0x55, 0x73, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0xb3,
	0x02, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x29, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f,
	0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x2e, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x12, 0x2c, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x52,
	0x65, 0x71, 0x48, 0x00, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x2c, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x71,
	0x48, 0x00, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x32, 0x0a,
	0x0c, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x2e, 0x52,
	0x65, 0x71, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x3c, 0x0a, 0x10, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x5f, 0x61, 0x6c,
	0x6c, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x52, 0x65,
	0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x41, 0x6c, 0x6c, 0x2e, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52,
	0x0e, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12,
	0x2c, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x71,
	0x48, 0x00, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x42, 0x05, 0x0a,
	0x03, 0x72, 0x65, 0x71, 0x1a, 0xb3, 0x02, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x09,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x08, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f,
	0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x0c, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x5f,
	0x72, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x52, 0x65, 0x74, 0x72,
	0x69, 0x65, 0x76, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x65, 0x74, 0x72,
	0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x10, 0x72, 0x65, 0x74, 0x72, 0x69,
	0x65, 0x76, 0x65, 0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x41, 0x6c, 0x6c, 0x2e,
	0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0e, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x41,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f,
	0x72, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x42, 0x05, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x22, 0x4d, 0x0a, 0x05, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x1a, 0x3d, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x1a, 0x05, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x22, 0x7d, 0x0a, 0x06, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x1a, 0x51, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x1a, 0x20, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x12, 0x19, 0x0a,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x4e, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x1a, 0x21, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x21, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4f, 0x0a, 0x08, 0x52, 0x65, 0x74, 0x72,
	0x69, 0x65, 0x76, 0x65, 0x1a, 0x21, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x20, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x12, 0x19,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x38, 0x0a, 0x0b, 0x52, 0x65, 0x74,
	0x72, 0x69, 0x65, 0x76, 0x65, 0x41, 0x6c, 0x6c, 0x1a, 0x05, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x1a,
	0x22, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x22, 0x7d, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x1a, 0x51, 0x0a,
	0x03, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65,
	0x1a, 0x20, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x22, 0x36, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x32, 0x4d, 0x0a, 0x0b, 0x4b, 0x47,
	0x4d, 0x53, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x12, 0x3e, 0x0a, 0x0e, 0x55, 0x73, 0x65,
	0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x13, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x71,
	0x1a, 0x13, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x52, 0x65, 0x73, 0x28, 0x01, 0x30, 0x01, 0x42, 0x50, 0x0a, 0x18, 0x67, 0x72, 0x61,
	0x6b, 0x6e, 0x2e, 0x6b, 0x67, 0x6d, 0x73, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x64, 0x42, 0x10, 0x4b, 0x47, 0x4d, 0x53, 0x43, 0x6f, 0x6e, 0x73, 0x6f,
	0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x22, 0x2e, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72,
	0x61, 0x6b, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x3b, 0x67, 0x72, 0x61,
	0x6b, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_v1_protobuf_console_proto_rawDescOnce sync.Once
	file_v1_protobuf_console_proto_rawDescData = file_v1_protobuf_console_proto_rawDesc
)

func file_v1_protobuf_console_proto_rawDescGZIP() []byte {
	file_v1_protobuf_console_proto_rawDescOnce.Do(func() {
		file_v1_protobuf_console_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_protobuf_console_proto_rawDescData)
	})
	return file_v1_protobuf_console_proto_rawDescData
}

var file_v1_protobuf_console_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_v1_protobuf_console_proto_goTypes = []interface{}{
	(*UserManagement)(nil),     // 0: UserManagement
	(*Login)(nil),              // 1: Login
	(*Create)(nil),             // 2: Create
	(*Delete)(nil),             // 3: Delete
	(*Retrieve)(nil),           // 4: Retrieve
	(*RetrieveAll)(nil),        // 5: RetrieveAll
	(*Update)(nil),             // 6: Update
	(*User)(nil),               // 7: User
	(*UserManagement_Req)(nil), // 8: UserManagement.Req
	(*UserManagement_Res)(nil), // 9: UserManagement.Res
	(*Login_Req)(nil),          // 10: Login.Req
	(*Login_Res)(nil),          // 11: Login.Res
	(*Create_Req)(nil),         // 12: Create.Req
	(*Create_Res)(nil),         // 13: Create.Res
	(*Delete_Req)(nil),         // 14: Delete.Req
	(*Delete_Res)(nil),         // 15: Delete.Res
	(*Retrieve_Req)(nil),       // 16: Retrieve.Req
	(*Retrieve_Res)(nil),       // 17: Retrieve.Res
	(*RetrieveAll_Req)(nil),    // 18: RetrieveAll.Req
	(*RetrieveAll_Res)(nil),    // 19: RetrieveAll.Res
	(*Update_Req)(nil),         // 20: Update.Req
	(*Update_Res)(nil),         // 21: Update.Res
}
var file_v1_protobuf_console_proto_depIdxs = []int32{
	10, // 0: UserManagement.Req.login_req:type_name -> Login.Req
	12, // 1: UserManagement.Req.create_req:type_name -> Create.Req
	14, // 2: UserManagement.Req.delete_req:type_name -> Delete.Req
	16, // 3: UserManagement.Req.retrieve_req:type_name -> Retrieve.Req
	18, // 4: UserManagement.Req.retrieve_all_req:type_name -> RetrieveAll.Req
	20, // 5: UserManagement.Req.update_req:type_name -> Update.Req
	11, // 6: UserManagement.Res.login_res:type_name -> Login.Res
	13, // 7: UserManagement.Res.create_res:type_name -> Create.Res
	15, // 8: UserManagement.Res.delete_res:type_name -> Delete.Res
	17, // 9: UserManagement.Res.retrieve_res:type_name -> Retrieve.Res
	19, // 10: UserManagement.Res.retrieve_all_res:type_name -> RetrieveAll.Res
	21, // 11: UserManagement.Res.update_res:type_name -> Update.Res
	7,  // 12: Create.Res.user:type_name -> User
	7,  // 13: Retrieve.Res.user:type_name -> User
	7,  // 14: RetrieveAll.Res.users:type_name -> User
	7,  // 15: Update.Res.user:type_name -> User
	8,  // 16: KGMSConsole.UserManagement:input_type -> UserManagement.Req
	9,  // 17: KGMSConsole.UserManagement:output_type -> UserManagement.Res
	17, // [17:18] is the sub-list for method output_type
	16, // [16:17] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_v1_protobuf_console_proto_init() }
func file_v1_protobuf_console_proto_init() {
	if File_v1_protobuf_console_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_protobuf_console_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserManagement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_protobuf_console_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_protobuf_console_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Create); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_protobuf_console_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Delete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_protobuf_console_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Retrieve); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_protobuf_console_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_protobuf_console_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_protobuf_console_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_protobuf_console_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserManagement_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_protobuf_console_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserManagement_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_protobuf_console_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Login_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_protobuf_console_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Login_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_protobuf_console_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Create_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_protobuf_console_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Create_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_protobuf_console_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Delete_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_protobuf_console_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Delete_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_protobuf_console_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Retrieve_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_protobuf_console_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Retrieve_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_protobuf_console_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveAll_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_protobuf_console_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveAll_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_protobuf_console_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Update_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_protobuf_console_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Update_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v1_protobuf_console_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*UserManagement_Req_LoginReq)(nil),
		(*UserManagement_Req_CreateReq)(nil),
		(*UserManagement_Req_DeleteReq)(nil),
		(*UserManagement_Req_RetrieveReq)(nil),
		(*UserManagement_Req_RetrieveAllReq)(nil),
		(*UserManagement_Req_UpdateReq)(nil),
	}
	file_v1_protobuf_console_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*UserManagement_Res_LoginRes)(nil),
		(*UserManagement_Res_CreateRes)(nil),
		(*UserManagement_Res_DeleteRes)(nil),
		(*UserManagement_Res_RetrieveRes)(nil),
		(*UserManagement_Res_RetrieveAllRes)(nil),
		(*UserManagement_Res_UpdateRes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_protobuf_console_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_protobuf_console_proto_goTypes,
		DependencyIndexes: file_v1_protobuf_console_proto_depIdxs,
		MessageInfos:      file_v1_protobuf_console_proto_msgTypes,
	}.Build()
	File_v1_protobuf_console_proto = out.File
	file_v1_protobuf_console_proto_rawDesc = nil
	file_v1_protobuf_console_proto_goTypes = nil
	file_v1_protobuf_console_proto_depIdxs = nil
}
