//
// Copyright (C) 2021 Grakn Labs
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: v2/protobuf/logic.proto

package grakn_protocol

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LogicManager struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogicManager) Reset() {
	*x = LogicManager{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_logic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicManager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicManager) ProtoMessage() {}

func (x *LogicManager) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_logic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicManager.ProtoReflect.Descriptor instead.
func (*LogicManager) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_logic_proto_rawDescGZIP(), []int{0}
}

type Rule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	When  string `protobuf:"bytes,2,opt,name=when,proto3" json:"when,omitempty"`
	Then  string `protobuf:"bytes,3,opt,name=then,proto3" json:"then,omitempty"`
}

func (x *Rule) Reset() {
	*x = Rule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_logic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_logic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_logic_proto_rawDescGZIP(), []int{1}
}

func (x *Rule) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Rule) GetWhen() string {
	if x != nil {
		return x.When
	}
	return ""
}

func (x *Rule) GetThen() string {
	if x != nil {
		return x.Then
	}
	return ""
}

type LogicManager_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Req:
	//	*LogicManager_Req_GetRuleReq
	//	*LogicManager_Req_PutRuleReq
	//	*LogicManager_Req_GetRulesReq
	Req isLogicManager_Req_Req `protobuf_oneof:"req"`
}

func (x *LogicManager_Req) Reset() {
	*x = LogicManager_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_logic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicManager_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicManager_Req) ProtoMessage() {}

func (x *LogicManager_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_logic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicManager_Req.ProtoReflect.Descriptor instead.
func (*LogicManager_Req) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_logic_proto_rawDescGZIP(), []int{0, 0}
}

func (m *LogicManager_Req) GetReq() isLogicManager_Req_Req {
	if m != nil {
		return m.Req
	}
	return nil
}

func (x *LogicManager_Req) GetGetRuleReq() *LogicManager_GetRule_Req {
	if x, ok := x.GetReq().(*LogicManager_Req_GetRuleReq); ok {
		return x.GetRuleReq
	}
	return nil
}

func (x *LogicManager_Req) GetPutRuleReq() *LogicManager_PutRule_Req {
	if x, ok := x.GetReq().(*LogicManager_Req_PutRuleReq); ok {
		return x.PutRuleReq
	}
	return nil
}

func (x *LogicManager_Req) GetGetRulesReq() *LogicManager_GetRules_Req {
	if x, ok := x.GetReq().(*LogicManager_Req_GetRulesReq); ok {
		return x.GetRulesReq
	}
	return nil
}

type isLogicManager_Req_Req interface {
	isLogicManager_Req_Req()
}

type LogicManager_Req_GetRuleReq struct {
	GetRuleReq *LogicManager_GetRule_Req `protobuf:"bytes,1,opt,name=get_rule_req,json=getRuleReq,proto3,oneof"`
}

type LogicManager_Req_PutRuleReq struct {
	PutRuleReq *LogicManager_PutRule_Req `protobuf:"bytes,2,opt,name=put_rule_req,json=putRuleReq,proto3,oneof"`
}

type LogicManager_Req_GetRulesReq struct {
	GetRulesReq *LogicManager_GetRules_Req `protobuf:"bytes,3,opt,name=get_rules_req,json=getRulesReq,proto3,oneof"`
}

func (*LogicManager_Req_GetRuleReq) isLogicManager_Req_Req() {}

func (*LogicManager_Req_PutRuleReq) isLogicManager_Req_Req() {}

func (*LogicManager_Req_GetRulesReq) isLogicManager_Req_Req() {}

type LogicManager_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Res:
	//	*LogicManager_Res_GetRuleRes
	//	*LogicManager_Res_PutRuleRes
	//	*LogicManager_Res_GetRulesRes
	Res isLogicManager_Res_Res `protobuf_oneof:"res"`
}

func (x *LogicManager_Res) Reset() {
	*x = LogicManager_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_logic_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicManager_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicManager_Res) ProtoMessage() {}

func (x *LogicManager_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_logic_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicManager_Res.ProtoReflect.Descriptor instead.
func (*LogicManager_Res) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_logic_proto_rawDescGZIP(), []int{0, 1}
}

func (m *LogicManager_Res) GetRes() isLogicManager_Res_Res {
	if m != nil {
		return m.Res
	}
	return nil
}

func (x *LogicManager_Res) GetGetRuleRes() *LogicManager_GetRule_Res {
	if x, ok := x.GetRes().(*LogicManager_Res_GetRuleRes); ok {
		return x.GetRuleRes
	}
	return nil
}

func (x *LogicManager_Res) GetPutRuleRes() *LogicManager_PutRule_Res {
	if x, ok := x.GetRes().(*LogicManager_Res_PutRuleRes); ok {
		return x.PutRuleRes
	}
	return nil
}

func (x *LogicManager_Res) GetGetRulesRes() *LogicManager_GetRules_Res {
	if x, ok := x.GetRes().(*LogicManager_Res_GetRulesRes); ok {
		return x.GetRulesRes
	}
	return nil
}

type isLogicManager_Res_Res interface {
	isLogicManager_Res_Res()
}

type LogicManager_Res_GetRuleRes struct {
	GetRuleRes *LogicManager_GetRule_Res `protobuf:"bytes,1,opt,name=get_rule_res,json=getRuleRes,proto3,oneof"`
}

type LogicManager_Res_PutRuleRes struct {
	PutRuleRes *LogicManager_PutRule_Res `protobuf:"bytes,2,opt,name=put_rule_res,json=putRuleRes,proto3,oneof"`
}

type LogicManager_Res_GetRulesRes struct {
	GetRulesRes *LogicManager_GetRules_Res `protobuf:"bytes,3,opt,name=get_rules_res,json=getRulesRes,proto3,oneof"`
}

func (*LogicManager_Res_GetRuleRes) isLogicManager_Res_Res() {}

func (*LogicManager_Res_PutRuleRes) isLogicManager_Res_Res() {}

func (*LogicManager_Res_GetRulesRes) isLogicManager_Res_Res() {}

type LogicManager_GetRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogicManager_GetRule) Reset() {
	*x = LogicManager_GetRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_logic_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicManager_GetRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicManager_GetRule) ProtoMessage() {}

func (x *LogicManager_GetRule) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_logic_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicManager_GetRule.ProtoReflect.Descriptor instead.
func (*LogicManager_GetRule) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_logic_proto_rawDescGZIP(), []int{0, 2}
}

type LogicManager_PutRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogicManager_PutRule) Reset() {
	*x = LogicManager_PutRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_logic_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicManager_PutRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicManager_PutRule) ProtoMessage() {}

func (x *LogicManager_PutRule) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_logic_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicManager_PutRule.ProtoReflect.Descriptor instead.
func (*LogicManager_PutRule) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_logic_proto_rawDescGZIP(), []int{0, 3}
}

type LogicManager_GetRules struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogicManager_GetRules) Reset() {
	*x = LogicManager_GetRules{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_logic_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicManager_GetRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicManager_GetRules) ProtoMessage() {}

func (x *LogicManager_GetRules) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_logic_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicManager_GetRules.ProtoReflect.Descriptor instead.
func (*LogicManager_GetRules) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_logic_proto_rawDescGZIP(), []int{0, 4}
}

type LogicManager_GetRule_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *LogicManager_GetRule_Req) Reset() {
	*x = LogicManager_GetRule_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_logic_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicManager_GetRule_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicManager_GetRule_Req) ProtoMessage() {}

func (x *LogicManager_GetRule_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_logic_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicManager_GetRule_Req.ProtoReflect.Descriptor instead.
func (*LogicManager_GetRule_Req) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_logic_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *LogicManager_GetRule_Req) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type LogicManager_GetRule_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Res:
	//	*LogicManager_GetRule_Res_Rule
	Res isLogicManager_GetRule_Res_Res `protobuf_oneof:"res"`
}

func (x *LogicManager_GetRule_Res) Reset() {
	*x = LogicManager_GetRule_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_logic_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicManager_GetRule_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicManager_GetRule_Res) ProtoMessage() {}

func (x *LogicManager_GetRule_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_logic_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicManager_GetRule_Res.ProtoReflect.Descriptor instead.
func (*LogicManager_GetRule_Res) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_logic_proto_rawDescGZIP(), []int{0, 2, 1}
}

func (m *LogicManager_GetRule_Res) GetRes() isLogicManager_GetRule_Res_Res {
	if m != nil {
		return m.Res
	}
	return nil
}

func (x *LogicManager_GetRule_Res) GetRule() *Rule {
	if x, ok := x.GetRes().(*LogicManager_GetRule_Res_Rule); ok {
		return x.Rule
	}
	return nil
}

type isLogicManager_GetRule_Res_Res interface {
	isLogicManager_GetRule_Res_Res()
}

type LogicManager_GetRule_Res_Rule struct {
	Rule *Rule `protobuf:"bytes,1,opt,name=rule,proto3,oneof"`
}

func (*LogicManager_GetRule_Res_Rule) isLogicManager_GetRule_Res_Res() {}

type LogicManager_PutRule_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	When  string `protobuf:"bytes,2,opt,name=when,proto3" json:"when,omitempty"`
	Then  string `protobuf:"bytes,3,opt,name=then,proto3" json:"then,omitempty"`
}

func (x *LogicManager_PutRule_Req) Reset() {
	*x = LogicManager_PutRule_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_logic_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicManager_PutRule_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicManager_PutRule_Req) ProtoMessage() {}

func (x *LogicManager_PutRule_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_logic_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicManager_PutRule_Req.ProtoReflect.Descriptor instead.
func (*LogicManager_PutRule_Req) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_logic_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (x *LogicManager_PutRule_Req) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *LogicManager_PutRule_Req) GetWhen() string {
	if x != nil {
		return x.When
	}
	return ""
}

func (x *LogicManager_PutRule_Req) GetThen() string {
	if x != nil {
		return x.Then
	}
	return ""
}

type LogicManager_PutRule_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rule *Rule `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
}

func (x *LogicManager_PutRule_Res) Reset() {
	*x = LogicManager_PutRule_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_logic_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicManager_PutRule_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicManager_PutRule_Res) ProtoMessage() {}

func (x *LogicManager_PutRule_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_logic_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicManager_PutRule_Res.ProtoReflect.Descriptor instead.
func (*LogicManager_PutRule_Res) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_logic_proto_rawDescGZIP(), []int{0, 3, 1}
}

func (x *LogicManager_PutRule_Res) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type LogicManager_GetRules_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogicManager_GetRules_Req) Reset() {
	*x = LogicManager_GetRules_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_logic_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicManager_GetRules_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicManager_GetRules_Req) ProtoMessage() {}

func (x *LogicManager_GetRules_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_logic_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicManager_GetRules_Req.ProtoReflect.Descriptor instead.
func (*LogicManager_GetRules_Req) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_logic_proto_rawDescGZIP(), []int{0, 4, 0}
}

type LogicManager_GetRules_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rules []*Rule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
}

func (x *LogicManager_GetRules_Res) Reset() {
	*x = LogicManager_GetRules_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_logic_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicManager_GetRules_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicManager_GetRules_Res) ProtoMessage() {}

func (x *LogicManager_GetRules_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_logic_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicManager_GetRules_Res.ProtoReflect.Descriptor instead.
func (*LogicManager_GetRules_Res) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_logic_proto_rawDescGZIP(), []int{0, 4, 1}
}

func (x *LogicManager_GetRules_Res) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type Rule_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// Types that are assignable to Req:
	//	*Rule_Req_RuleDeleteReq
	//	*Rule_Req_RuleSetLabelReq
	Req isRule_Req_Req `protobuf_oneof:"req"`
}

func (x *Rule_Req) Reset() {
	*x = Rule_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_logic_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rule_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule_Req) ProtoMessage() {}

func (x *Rule_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_logic_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule_Req.ProtoReflect.Descriptor instead.
func (*Rule_Req) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_logic_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Rule_Req) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (m *Rule_Req) GetReq() isRule_Req_Req {
	if m != nil {
		return m.Req
	}
	return nil
}

func (x *Rule_Req) GetRuleDeleteReq() *Rule_Delete_Req {
	if x, ok := x.GetReq().(*Rule_Req_RuleDeleteReq); ok {
		return x.RuleDeleteReq
	}
	return nil
}

func (x *Rule_Req) GetRuleSetLabelReq() *Rule_SetLabel_Req {
	if x, ok := x.GetReq().(*Rule_Req_RuleSetLabelReq); ok {
		return x.RuleSetLabelReq
	}
	return nil
}

type isRule_Req_Req interface {
	isRule_Req_Req()
}

type Rule_Req_RuleDeleteReq struct {
	RuleDeleteReq *Rule_Delete_Req `protobuf:"bytes,100,opt,name=rule_delete_req,json=ruleDeleteReq,proto3,oneof"`
}

type Rule_Req_RuleSetLabelReq struct {
	RuleSetLabelReq *Rule_SetLabel_Req `protobuf:"bytes,101,opt,name=rule_set_label_req,json=ruleSetLabelReq,proto3,oneof"`
}

func (*Rule_Req_RuleDeleteReq) isRule_Req_Req() {}

func (*Rule_Req_RuleSetLabelReq) isRule_Req_Req() {}

type Rule_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Res:
	//	*Rule_Res_RuleDeleteRes
	//	*Rule_Res_RuleSetLabelRes
	Res isRule_Res_Res `protobuf_oneof:"res"`
}

func (x *Rule_Res) Reset() {
	*x = Rule_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_logic_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rule_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule_Res) ProtoMessage() {}

func (x *Rule_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_logic_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule_Res.ProtoReflect.Descriptor instead.
func (*Rule_Res) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_logic_proto_rawDescGZIP(), []int{1, 1}
}

func (m *Rule_Res) GetRes() isRule_Res_Res {
	if m != nil {
		return m.Res
	}
	return nil
}

func (x *Rule_Res) GetRuleDeleteRes() *Rule_Delete_Res {
	if x, ok := x.GetRes().(*Rule_Res_RuleDeleteRes); ok {
		return x.RuleDeleteRes
	}
	return nil
}

func (x *Rule_Res) GetRuleSetLabelRes() *Rule_SetLabel_Res {
	if x, ok := x.GetRes().(*Rule_Res_RuleSetLabelRes); ok {
		return x.RuleSetLabelRes
	}
	return nil
}

type isRule_Res_Res interface {
	isRule_Res_Res()
}

type Rule_Res_RuleDeleteRes struct {
	RuleDeleteRes *Rule_Delete_Res `protobuf:"bytes,100,opt,name=rule_delete_res,json=ruleDeleteRes,proto3,oneof"`
}

type Rule_Res_RuleSetLabelRes struct {
	RuleSetLabelRes *Rule_SetLabel_Res `protobuf:"bytes,101,opt,name=rule_set_label_res,json=ruleSetLabelRes,proto3,oneof"`
}

func (*Rule_Res_RuleDeleteRes) isRule_Res_Res() {}

func (*Rule_Res_RuleSetLabelRes) isRule_Res_Res() {}

type Rule_Delete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Rule_Delete) Reset() {
	*x = Rule_Delete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_logic_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rule_Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule_Delete) ProtoMessage() {}

func (x *Rule_Delete) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_logic_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule_Delete.ProtoReflect.Descriptor instead.
func (*Rule_Delete) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_logic_proto_rawDescGZIP(), []int{1, 2}
}

type Rule_SetLabel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Rule_SetLabel) Reset() {
	*x = Rule_SetLabel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_logic_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rule_SetLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule_SetLabel) ProtoMessage() {}

func (x *Rule_SetLabel) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_logic_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule_SetLabel.ProtoReflect.Descriptor instead.
func (*Rule_SetLabel) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_logic_proto_rawDescGZIP(), []int{1, 3}
}

type Rule_Delete_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Rule_Delete_Req) Reset() {
	*x = Rule_Delete_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_logic_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rule_Delete_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule_Delete_Req) ProtoMessage() {}

func (x *Rule_Delete_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_logic_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule_Delete_Req.ProtoReflect.Descriptor instead.
func (*Rule_Delete_Req) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_logic_proto_rawDescGZIP(), []int{1, 2, 0}
}

type Rule_Delete_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Rule_Delete_Res) Reset() {
	*x = Rule_Delete_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_logic_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rule_Delete_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule_Delete_Res) ProtoMessage() {}

func (x *Rule_Delete_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_logic_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule_Delete_Res.ProtoReflect.Descriptor instead.
func (*Rule_Delete_Res) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_logic_proto_rawDescGZIP(), []int{1, 2, 1}
}

type Rule_SetLabel_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *Rule_SetLabel_Req) Reset() {
	*x = Rule_SetLabel_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_logic_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rule_SetLabel_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule_SetLabel_Req) ProtoMessage() {}

func (x *Rule_SetLabel_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_logic_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule_SetLabel_Req.ProtoReflect.Descriptor instead.
func (*Rule_SetLabel_Req) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_logic_proto_rawDescGZIP(), []int{1, 3, 0}
}

func (x *Rule_SetLabel_Req) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type Rule_SetLabel_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Rule_SetLabel_Res) Reset() {
	*x = Rule_SetLabel_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_logic_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rule_SetLabel_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule_SetLabel_Res) ProtoMessage() {}

func (x *Rule_SetLabel_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_logic_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule_SetLabel_Res.ProtoReflect.Descriptor instead.
func (*Rule_SetLabel_Res) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_logic_proto_rawDescGZIP(), []int{1, 3, 1}
}

var File_v2_protobuf_logic_proto protoreflect.FileDescriptor

var file_v2_protobuf_logic_proto_rawDesc = []byte{
	0x0a, 0x17, 0x76, 0x32, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6c, 0x6f,
	0x67, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x67, 0x72, 0x61, 0x6b, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0xaf, 0x06, 0x0a, 0x0c, 0x4c, 0x6f,
	0x67, 0x69, 0x63, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x1a, 0xf9, 0x01, 0x0a, 0x03, 0x52,
	0x65, 0x71, 0x12, 0x4c, 0x0a, 0x0c, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x72,
	0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x4d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x2e, 0x52,
	0x65, 0x71, 0x48, 0x00, 0x52, 0x0a, 0x67, 0x65, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x4c, 0x0a, 0x0c, 0x70, 0x75, 0x74, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x72, 0x65, 0x71,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x2e, 0x52, 0x65, 0x71,
	0x48, 0x00, 0x52, 0x0a, 0x70, 0x75, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x4f,
	0x0a, 0x0d, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x71,
	0x48, 0x00, 0x52, 0x0b, 0x67, 0x65, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x42,
	0x05, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x1a, 0xf9, 0x01, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x12, 0x4c,
	0x0a, 0x0c, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x48, 0x00,
	0x52, 0x0a, 0x67, 0x65, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x12, 0x4c, 0x0a, 0x0c,
	0x70, 0x75, 0x74, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x28, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2e, 0x50, 0x75, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0a,
	0x70, 0x75, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x12, 0x4f, 0x0a, 0x0d, 0x67, 0x65,
	0x74, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x29, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0b,
	0x67, 0x65, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x42, 0x05, 0x0a, 0x03, 0x72,
	0x65, 0x73, 0x1a, 0x60, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x1a, 0x1b, 0x0a,
	0x03, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x1a, 0x38, 0x0a, 0x03, 0x52, 0x65,
	0x73, 0x12, 0x2a, 0x0a, 0x04, 0x72, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x52, 0x75, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x04, 0x72, 0x75, 0x6c, 0x65, 0x42, 0x05, 0x0a,
	0x03, 0x72, 0x65, 0x73, 0x1a, 0x7f, 0x0a, 0x07, 0x50, 0x75, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x1a,
	0x43, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x77, 0x68, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x68, 0x65, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x68, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x68, 0x65, 0x6e, 0x1a, 0x2f, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x04, 0x72,
	0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x72, 0x61, 0x6b,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x52,
	0x04, 0x72, 0x75, 0x6c, 0x65, 0x1a, 0x44, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6c, 0x65,
	0x73, 0x1a, 0x05, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x1a, 0x31, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x12,
	0x2a, 0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x52, 0x75, 0x6c, 0x65, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x22, 0xfa, 0x03, 0x0a, 0x04,
	0x52, 0x75, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x68,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x68, 0x65, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x68, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x68,
	0x65, 0x6e, 0x1a, 0xbf, 0x01, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x12, 0x49, 0x0a, 0x0f, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f,
	0x72, 0x65, 0x71, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x72, 0x61, 0x6b,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x75,
	0x6c, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x50, 0x0a, 0x12, 0x72,
	0x75, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x5f, 0x72, 0x65,
	0x71, 0x18, 0x65, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x2e, 0x53, 0x65,
	0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x0f, 0x72, 0x75,
	0x6c, 0x65, 0x53, 0x65, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x42, 0x05, 0x0a,
	0x03, 0x72, 0x65, 0x71, 0x1a, 0xa9, 0x01, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x12, 0x49, 0x0a, 0x0f,
	0x72, 0x75, 0x6c, 0x65, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x18,
	0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x75, 0x6c, 0x65, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x50, 0x0a, 0x12, 0x72, 0x75, 0x6c, 0x65, 0x5f,
	0x73, 0x65, 0x74, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x65, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0f, 0x72, 0x75, 0x6c, 0x65, 0x53, 0x65,
	0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x42, 0x05, 0x0a, 0x03, 0x72, 0x65, 0x73,
	0x1a, 0x16, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x1a, 0x05, 0x0a, 0x03, 0x52, 0x65,
	0x71, 0x1a, 0x05, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x1a, 0x2e, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x1a, 0x1b, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x1a, 0x05, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x42, 0x40, 0x0a, 0x0e, 0x67, 0x72, 0x61, 0x6b,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x42, 0x0a, 0x4c, 0x6f, 0x67, 0x69,
	0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x22, 0x2e, 0x2f, 0x76, 0x32, 0x2f, 0x67, 0x72, 0x61,
	0x6b, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x3b, 0x67, 0x72, 0x61, 0x6b,
	0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_v2_protobuf_logic_proto_rawDescOnce sync.Once
	file_v2_protobuf_logic_proto_rawDescData = file_v2_protobuf_logic_proto_rawDesc
)

func file_v2_protobuf_logic_proto_rawDescGZIP() []byte {
	file_v2_protobuf_logic_proto_rawDescOnce.Do(func() {
		file_v2_protobuf_logic_proto_rawDescData = protoimpl.X.CompressGZIP(file_v2_protobuf_logic_proto_rawDescData)
	})
	return file_v2_protobuf_logic_proto_rawDescData
}

var file_v2_protobuf_logic_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_v2_protobuf_logic_proto_goTypes = []interface{}{
	(*LogicManager)(nil),              // 0: grakn.protocol.LogicManager
	(*Rule)(nil),                      // 1: grakn.protocol.Rule
	(*LogicManager_Req)(nil),          // 2: grakn.protocol.LogicManager.Req
	(*LogicManager_Res)(nil),          // 3: grakn.protocol.LogicManager.Res
	(*LogicManager_GetRule)(nil),      // 4: grakn.protocol.LogicManager.GetRule
	(*LogicManager_PutRule)(nil),      // 5: grakn.protocol.LogicManager.PutRule
	(*LogicManager_GetRules)(nil),     // 6: grakn.protocol.LogicManager.GetRules
	(*LogicManager_GetRule_Req)(nil),  // 7: grakn.protocol.LogicManager.GetRule.Req
	(*LogicManager_GetRule_Res)(nil),  // 8: grakn.protocol.LogicManager.GetRule.Res
	(*LogicManager_PutRule_Req)(nil),  // 9: grakn.protocol.LogicManager.PutRule.Req
	(*LogicManager_PutRule_Res)(nil),  // 10: grakn.protocol.LogicManager.PutRule.Res
	(*LogicManager_GetRules_Req)(nil), // 11: grakn.protocol.LogicManager.GetRules.Req
	(*LogicManager_GetRules_Res)(nil), // 12: grakn.protocol.LogicManager.GetRules.Res
	(*Rule_Req)(nil),                  // 13: grakn.protocol.Rule.Req
	(*Rule_Res)(nil),                  // 14: grakn.protocol.Rule.Res
	(*Rule_Delete)(nil),               // 15: grakn.protocol.Rule.Delete
	(*Rule_SetLabel)(nil),             // 16: grakn.protocol.Rule.SetLabel
	(*Rule_Delete_Req)(nil),           // 17: grakn.protocol.Rule.Delete.Req
	(*Rule_Delete_Res)(nil),           // 18: grakn.protocol.Rule.Delete.Res
	(*Rule_SetLabel_Req)(nil),         // 19: grakn.protocol.Rule.SetLabel.Req
	(*Rule_SetLabel_Res)(nil),         // 20: grakn.protocol.Rule.SetLabel.Res
}
var file_v2_protobuf_logic_proto_depIdxs = []int32{
	7,  // 0: grakn.protocol.LogicManager.Req.get_rule_req:type_name -> grakn.protocol.LogicManager.GetRule.Req
	9,  // 1: grakn.protocol.LogicManager.Req.put_rule_req:type_name -> grakn.protocol.LogicManager.PutRule.Req
	11, // 2: grakn.protocol.LogicManager.Req.get_rules_req:type_name -> grakn.protocol.LogicManager.GetRules.Req
	8,  // 3: grakn.protocol.LogicManager.Res.get_rule_res:type_name -> grakn.protocol.LogicManager.GetRule.Res
	10, // 4: grakn.protocol.LogicManager.Res.put_rule_res:type_name -> grakn.protocol.LogicManager.PutRule.Res
	12, // 5: grakn.protocol.LogicManager.Res.get_rules_res:type_name -> grakn.protocol.LogicManager.GetRules.Res
	1,  // 6: grakn.protocol.LogicManager.GetRule.Res.rule:type_name -> grakn.protocol.Rule
	1,  // 7: grakn.protocol.LogicManager.PutRule.Res.rule:type_name -> grakn.protocol.Rule
	1,  // 8: grakn.protocol.LogicManager.GetRules.Res.rules:type_name -> grakn.protocol.Rule
	17, // 9: grakn.protocol.Rule.Req.rule_delete_req:type_name -> grakn.protocol.Rule.Delete.Req
	19, // 10: grakn.protocol.Rule.Req.rule_set_label_req:type_name -> grakn.protocol.Rule.SetLabel.Req
	18, // 11: grakn.protocol.Rule.Res.rule_delete_res:type_name -> grakn.protocol.Rule.Delete.Res
	20, // 12: grakn.protocol.Rule.Res.rule_set_label_res:type_name -> grakn.protocol.Rule.SetLabel.Res
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_v2_protobuf_logic_proto_init() }
func file_v2_protobuf_logic_proto_init() {
	if File_v2_protobuf_logic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v2_protobuf_logic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogicManager); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_logic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_logic_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogicManager_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_logic_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogicManager_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_logic_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogicManager_GetRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_logic_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogicManager_PutRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_logic_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogicManager_GetRules); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_logic_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogicManager_GetRule_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_logic_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogicManager_GetRule_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_logic_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogicManager_PutRule_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_logic_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogicManager_PutRule_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_logic_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogicManager_GetRules_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_logic_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogicManager_GetRules_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_logic_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rule_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_logic_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rule_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_logic_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rule_Delete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_logic_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rule_SetLabel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_logic_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rule_Delete_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_logic_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rule_Delete_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_logic_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rule_SetLabel_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_logic_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rule_SetLabel_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v2_protobuf_logic_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*LogicManager_Req_GetRuleReq)(nil),
		(*LogicManager_Req_PutRuleReq)(nil),
		(*LogicManager_Req_GetRulesReq)(nil),
	}
	file_v2_protobuf_logic_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*LogicManager_Res_GetRuleRes)(nil),
		(*LogicManager_Res_PutRuleRes)(nil),
		(*LogicManager_Res_GetRulesRes)(nil),
	}
	file_v2_protobuf_logic_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*LogicManager_GetRule_Res_Rule)(nil),
	}
	file_v2_protobuf_logic_proto_msgTypes[13].OneofWrappers = []interface{}{
		(*Rule_Req_RuleDeleteReq)(nil),
		(*Rule_Req_RuleSetLabelReq)(nil),
	}
	file_v2_protobuf_logic_proto_msgTypes[14].OneofWrappers = []interface{}{
		(*Rule_Res_RuleDeleteRes)(nil),
		(*Rule_Res_RuleSetLabelRes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v2_protobuf_logic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_protobuf_logic_proto_goTypes,
		DependencyIndexes: file_v2_protobuf_logic_proto_depIdxs,
		MessageInfos:      file_v2_protobuf_logic_proto_msgTypes,
	}.Build()
	File_v2_protobuf_logic_proto = out.File
	file_v2_protobuf_logic_proto_rawDesc = nil
	file_v2_protobuf_logic_proto_goTypes = nil
	file_v2_protobuf_logic_proto_depIdxs = nil
}
