//
// Copyright (C) 2021 Grakn Labs
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: v2/protobuf/query.proto

package grakn_protocol

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Query struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Query) Reset() {
	*x = Query{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0}
}

type Query_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options *Options `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	// Types that are assignable to Req:
	//	*Query_Req_DefineReq
	//	*Query_Req_UndefineReq
	//	*Query_Req_MatchReq
	//	*Query_Req_MatchAggregateReq
	//	*Query_Req_MatchGroupReq
	//	*Query_Req_MatchGroupAggregateReq
	//	*Query_Req_InsertReq
	//	*Query_Req_DeleteReq
	//	*Query_Req_UpdateReq
	Req isQuery_Req_Req `protobuf_oneof:"req"`
}

func (x *Query_Req) Reset() {
	*x = Query_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Req) ProtoMessage() {}

func (x *Query_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Req.ProtoReflect.Descriptor instead.
func (*Query_Req) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Query_Req) GetOptions() *Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (m *Query_Req) GetReq() isQuery_Req_Req {
	if m != nil {
		return m.Req
	}
	return nil
}

func (x *Query_Req) GetDefineReq() *Query_Define_Req {
	if x, ok := x.GetReq().(*Query_Req_DefineReq); ok {
		return x.DefineReq
	}
	return nil
}

func (x *Query_Req) GetUndefineReq() *Query_Undefine_Req {
	if x, ok := x.GetReq().(*Query_Req_UndefineReq); ok {
		return x.UndefineReq
	}
	return nil
}

func (x *Query_Req) GetMatchReq() *Query_Match_Req {
	if x, ok := x.GetReq().(*Query_Req_MatchReq); ok {
		return x.MatchReq
	}
	return nil
}

func (x *Query_Req) GetMatchAggregateReq() *Query_MatchAggregate_Req {
	if x, ok := x.GetReq().(*Query_Req_MatchAggregateReq); ok {
		return x.MatchAggregateReq
	}
	return nil
}

func (x *Query_Req) GetMatchGroupReq() *Query_MatchGroup_Req {
	if x, ok := x.GetReq().(*Query_Req_MatchGroupReq); ok {
		return x.MatchGroupReq
	}
	return nil
}

func (x *Query_Req) GetMatchGroupAggregateReq() *Query_MatchGroupAggregate_Req {
	if x, ok := x.GetReq().(*Query_Req_MatchGroupAggregateReq); ok {
		return x.MatchGroupAggregateReq
	}
	return nil
}

func (x *Query_Req) GetInsertReq() *Query_Insert_Req {
	if x, ok := x.GetReq().(*Query_Req_InsertReq); ok {
		return x.InsertReq
	}
	return nil
}

func (x *Query_Req) GetDeleteReq() *Query_Delete_Req {
	if x, ok := x.GetReq().(*Query_Req_DeleteReq); ok {
		return x.DeleteReq
	}
	return nil
}

func (x *Query_Req) GetUpdateReq() *Query_Update_Req {
	if x, ok := x.GetReq().(*Query_Req_UpdateReq); ok {
		return x.UpdateReq
	}
	return nil
}

type isQuery_Req_Req interface {
	isQuery_Req_Req()
}

type Query_Req_DefineReq struct {
	DefineReq *Query_Define_Req `protobuf:"bytes,100,opt,name=define_req,json=defineReq,proto3,oneof"`
}

type Query_Req_UndefineReq struct {
	UndefineReq *Query_Undefine_Req `protobuf:"bytes,101,opt,name=undefine_req,json=undefineReq,proto3,oneof"`
}

type Query_Req_MatchReq struct {
	MatchReq *Query_Match_Req `protobuf:"bytes,102,opt,name=match_req,json=matchReq,proto3,oneof"`
}

type Query_Req_MatchAggregateReq struct {
	MatchAggregateReq *Query_MatchAggregate_Req `protobuf:"bytes,103,opt,name=match_aggregate_req,json=matchAggregateReq,proto3,oneof"`
}

type Query_Req_MatchGroupReq struct {
	MatchGroupReq *Query_MatchGroup_Req `protobuf:"bytes,104,opt,name=match_group_req,json=matchGroupReq,proto3,oneof"`
}

type Query_Req_MatchGroupAggregateReq struct {
	MatchGroupAggregateReq *Query_MatchGroupAggregate_Req `protobuf:"bytes,105,opt,name=match_group_aggregate_req,json=matchGroupAggregateReq,proto3,oneof"`
}

type Query_Req_InsertReq struct {
	InsertReq *Query_Insert_Req `protobuf:"bytes,106,opt,name=insert_req,json=insertReq,proto3,oneof"`
}

type Query_Req_DeleteReq struct {
	DeleteReq *Query_Delete_Req `protobuf:"bytes,107,opt,name=delete_req,json=deleteReq,proto3,oneof"`
}

type Query_Req_UpdateReq struct {
	UpdateReq *Query_Update_Req `protobuf:"bytes,108,opt,name=update_req,json=updateReq,proto3,oneof"`
}

func (*Query_Req_DefineReq) isQuery_Req_Req() {}

func (*Query_Req_UndefineReq) isQuery_Req_Req() {}

func (*Query_Req_MatchReq) isQuery_Req_Req() {}

func (*Query_Req_MatchAggregateReq) isQuery_Req_Req() {}

func (*Query_Req_MatchGroupReq) isQuery_Req_Req() {}

func (*Query_Req_MatchGroupAggregateReq) isQuery_Req_Req() {}

func (*Query_Req_InsertReq) isQuery_Req_Req() {}

func (*Query_Req_DeleteReq) isQuery_Req_Req() {}

func (*Query_Req_UpdateReq) isQuery_Req_Req() {}

type Query_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Res:
	//	*Query_Res_DefineRes
	//	*Query_Res_UndefineRes
	//	*Query_Res_MatchRes
	//	*Query_Res_MatchAggregateRes
	//	*Query_Res_MatchGroupRes
	//	*Query_Res_MatchGroupAggregateRes
	//	*Query_Res_InsertRes
	//	*Query_Res_DeleteRes
	//	*Query_Res_UpdateRes
	Res isQuery_Res_Res `protobuf_oneof:"res"`
}

func (x *Query_Res) Reset() {
	*x = Query_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Res) ProtoMessage() {}

func (x *Query_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Res.ProtoReflect.Descriptor instead.
func (*Query_Res) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 1}
}

func (m *Query_Res) GetRes() isQuery_Res_Res {
	if m != nil {
		return m.Res
	}
	return nil
}

func (x *Query_Res) GetDefineRes() *Query_Define_Res {
	if x, ok := x.GetRes().(*Query_Res_DefineRes); ok {
		return x.DefineRes
	}
	return nil
}

func (x *Query_Res) GetUndefineRes() *Query_Undefine_Res {
	if x, ok := x.GetRes().(*Query_Res_UndefineRes); ok {
		return x.UndefineRes
	}
	return nil
}

func (x *Query_Res) GetMatchRes() *Query_Match_Res {
	if x, ok := x.GetRes().(*Query_Res_MatchRes); ok {
		return x.MatchRes
	}
	return nil
}

func (x *Query_Res) GetMatchAggregateRes() *Query_MatchAggregate_Res {
	if x, ok := x.GetRes().(*Query_Res_MatchAggregateRes); ok {
		return x.MatchAggregateRes
	}
	return nil
}

func (x *Query_Res) GetMatchGroupRes() *Query_MatchGroup_Res {
	if x, ok := x.GetRes().(*Query_Res_MatchGroupRes); ok {
		return x.MatchGroupRes
	}
	return nil
}

func (x *Query_Res) GetMatchGroupAggregateRes() *Query_MatchGroupAggregate_Res {
	if x, ok := x.GetRes().(*Query_Res_MatchGroupAggregateRes); ok {
		return x.MatchGroupAggregateRes
	}
	return nil
}

func (x *Query_Res) GetInsertRes() *Query_Insert_Res {
	if x, ok := x.GetRes().(*Query_Res_InsertRes); ok {
		return x.InsertRes
	}
	return nil
}

func (x *Query_Res) GetDeleteRes() *Query_Delete_Res {
	if x, ok := x.GetRes().(*Query_Res_DeleteRes); ok {
		return x.DeleteRes
	}
	return nil
}

func (x *Query_Res) GetUpdateRes() *Query_Update_Res {
	if x, ok := x.GetRes().(*Query_Res_UpdateRes); ok {
		return x.UpdateRes
	}
	return nil
}

type isQuery_Res_Res interface {
	isQuery_Res_Res()
}

type Query_Res_DefineRes struct {
	DefineRes *Query_Define_Res `protobuf:"bytes,100,opt,name=define_res,json=defineRes,proto3,oneof"`
}

type Query_Res_UndefineRes struct {
	UndefineRes *Query_Undefine_Res `protobuf:"bytes,101,opt,name=undefine_res,json=undefineRes,proto3,oneof"`
}

type Query_Res_MatchRes struct {
	MatchRes *Query_Match_Res `protobuf:"bytes,102,opt,name=match_res,json=matchRes,proto3,oneof"`
}

type Query_Res_MatchAggregateRes struct {
	MatchAggregateRes *Query_MatchAggregate_Res `protobuf:"bytes,103,opt,name=match_aggregate_res,json=matchAggregateRes,proto3,oneof"`
}

type Query_Res_MatchGroupRes struct {
	MatchGroupRes *Query_MatchGroup_Res `protobuf:"bytes,104,opt,name=match_group_res,json=matchGroupRes,proto3,oneof"`
}

type Query_Res_MatchGroupAggregateRes struct {
	MatchGroupAggregateRes *Query_MatchGroupAggregate_Res `protobuf:"bytes,105,opt,name=match_group_aggregate_res,json=matchGroupAggregateRes,proto3,oneof"`
}

type Query_Res_InsertRes struct {
	InsertRes *Query_Insert_Res `protobuf:"bytes,106,opt,name=insert_res,json=insertRes,proto3,oneof"`
}

type Query_Res_DeleteRes struct {
	DeleteRes *Query_Delete_Res `protobuf:"bytes,107,opt,name=delete_res,json=deleteRes,proto3,oneof"`
}

type Query_Res_UpdateRes struct {
	UpdateRes *Query_Update_Res `protobuf:"bytes,108,opt,name=update_res,json=updateRes,proto3,oneof"`
}

func (*Query_Res_DefineRes) isQuery_Res_Res() {}

func (*Query_Res_UndefineRes) isQuery_Res_Res() {}

func (*Query_Res_MatchRes) isQuery_Res_Res() {}

func (*Query_Res_MatchAggregateRes) isQuery_Res_Res() {}

func (*Query_Res_MatchGroupRes) isQuery_Res_Res() {}

func (*Query_Res_MatchGroupAggregateRes) isQuery_Res_Res() {}

func (*Query_Res_InsertRes) isQuery_Res_Res() {}

func (*Query_Res_DeleteRes) isQuery_Res_Res() {}

func (*Query_Res_UpdateRes) isQuery_Res_Res() {}

type Query_Match struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Query_Match) Reset() {
	*x = Query_Match{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Match) ProtoMessage() {}

func (x *Query_Match) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Match.ProtoReflect.Descriptor instead.
func (*Query_Match) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 2}
}

type Query_MatchAggregate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Query_MatchAggregate) Reset() {
	*x = Query_MatchAggregate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_MatchAggregate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_MatchAggregate) ProtoMessage() {}

func (x *Query_MatchAggregate) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_MatchAggregate.ProtoReflect.Descriptor instead.
func (*Query_MatchAggregate) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 3}
}

type Query_MatchGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Query_MatchGroup) Reset() {
	*x = Query_MatchGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_MatchGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_MatchGroup) ProtoMessage() {}

func (x *Query_MatchGroup) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_MatchGroup.ProtoReflect.Descriptor instead.
func (*Query_MatchGroup) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 4}
}

type Query_MatchGroupAggregate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Query_MatchGroupAggregate) Reset() {
	*x = Query_MatchGroupAggregate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_MatchGroupAggregate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_MatchGroupAggregate) ProtoMessage() {}

func (x *Query_MatchGroupAggregate) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_MatchGroupAggregate.ProtoReflect.Descriptor instead.
func (*Query_MatchGroupAggregate) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 5}
}

type Query_Insert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Query_Insert) Reset() {
	*x = Query_Insert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Insert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Insert) ProtoMessage() {}

func (x *Query_Insert) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Insert.ProtoReflect.Descriptor instead.
func (*Query_Insert) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 6}
}

type Query_Delete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Query_Delete) Reset() {
	*x = Query_Delete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Delete) ProtoMessage() {}

func (x *Query_Delete) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Delete.ProtoReflect.Descriptor instead.
func (*Query_Delete) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 7}
}

type Query_Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Query_Update) Reset() {
	*x = Query_Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Update) ProtoMessage() {}

func (x *Query_Update) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Update.ProtoReflect.Descriptor instead.
func (*Query_Update) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 8}
}

type Query_Define struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Query_Define) Reset() {
	*x = Query_Define{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Define) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Define) ProtoMessage() {}

func (x *Query_Define) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Define.ProtoReflect.Descriptor instead.
func (*Query_Define) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 9}
}

type Query_Undefine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Query_Undefine) Reset() {
	*x = Query_Undefine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Undefine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Undefine) ProtoMessage() {}

func (x *Query_Undefine) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Undefine.ProtoReflect.Descriptor instead.
func (*Query_Undefine) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 10}
}

type Query_Match_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *Query_Match_Req) Reset() {
	*x = Query_Match_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Match_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Match_Req) ProtoMessage() {}

func (x *Query_Match_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Match_Req.ProtoReflect.Descriptor instead.
func (*Query_Match_Req) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *Query_Match_Req) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type Query_Match_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answers []*ConceptMap `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
}

func (x *Query_Match_Res) Reset() {
	*x = Query_Match_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Match_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Match_Res) ProtoMessage() {}

func (x *Query_Match_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Match_Res.ProtoReflect.Descriptor instead.
func (*Query_Match_Res) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 2, 1}
}

func (x *Query_Match_Res) GetAnswers() []*ConceptMap {
	if x != nil {
		return x.Answers
	}
	return nil
}

type Query_MatchAggregate_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *Query_MatchAggregate_Req) Reset() {
	*x = Query_MatchAggregate_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_MatchAggregate_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_MatchAggregate_Req) ProtoMessage() {}

func (x *Query_MatchAggregate_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_MatchAggregate_Req.ProtoReflect.Descriptor instead.
func (*Query_MatchAggregate_Req) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (x *Query_MatchAggregate_Req) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type Query_MatchAggregate_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer *Numeric `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *Query_MatchAggregate_Res) Reset() {
	*x = Query_MatchAggregate_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_MatchAggregate_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_MatchAggregate_Res) ProtoMessage() {}

func (x *Query_MatchAggregate_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_MatchAggregate_Res.ProtoReflect.Descriptor instead.
func (*Query_MatchAggregate_Res) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 3, 1}
}

func (x *Query_MatchAggregate_Res) GetAnswer() *Numeric {
	if x != nil {
		return x.Answer
	}
	return nil
}

type Query_MatchGroup_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *Query_MatchGroup_Req) Reset() {
	*x = Query_MatchGroup_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_MatchGroup_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_MatchGroup_Req) ProtoMessage() {}

func (x *Query_MatchGroup_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_MatchGroup_Req.ProtoReflect.Descriptor instead.
func (*Query_MatchGroup_Req) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 4, 0}
}

func (x *Query_MatchGroup_Req) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type Query_MatchGroup_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answers []*ConceptMapGroup `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
}

func (x *Query_MatchGroup_Res) Reset() {
	*x = Query_MatchGroup_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_MatchGroup_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_MatchGroup_Res) ProtoMessage() {}

func (x *Query_MatchGroup_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_MatchGroup_Res.ProtoReflect.Descriptor instead.
func (*Query_MatchGroup_Res) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 4, 1}
}

func (x *Query_MatchGroup_Res) GetAnswers() []*ConceptMapGroup {
	if x != nil {
		return x.Answers
	}
	return nil
}

type Query_MatchGroupAggregate_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *Query_MatchGroupAggregate_Req) Reset() {
	*x = Query_MatchGroupAggregate_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_MatchGroupAggregate_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_MatchGroupAggregate_Req) ProtoMessage() {}

func (x *Query_MatchGroupAggregate_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_MatchGroupAggregate_Req.ProtoReflect.Descriptor instead.
func (*Query_MatchGroupAggregate_Req) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 5, 0}
}

func (x *Query_MatchGroupAggregate_Req) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type Query_MatchGroupAggregate_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answers []*NumericGroup `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
}

func (x *Query_MatchGroupAggregate_Res) Reset() {
	*x = Query_MatchGroupAggregate_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_MatchGroupAggregate_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_MatchGroupAggregate_Res) ProtoMessage() {}

func (x *Query_MatchGroupAggregate_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_MatchGroupAggregate_Res.ProtoReflect.Descriptor instead.
func (*Query_MatchGroupAggregate_Res) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 5, 1}
}

func (x *Query_MatchGroupAggregate_Res) GetAnswers() []*NumericGroup {
	if x != nil {
		return x.Answers
	}
	return nil
}

type Query_Insert_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *Query_Insert_Req) Reset() {
	*x = Query_Insert_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Insert_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Insert_Req) ProtoMessage() {}

func (x *Query_Insert_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Insert_Req.ProtoReflect.Descriptor instead.
func (*Query_Insert_Req) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 6, 0}
}

func (x *Query_Insert_Req) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type Query_Insert_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answers []*ConceptMap `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
}

func (x *Query_Insert_Res) Reset() {
	*x = Query_Insert_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Insert_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Insert_Res) ProtoMessage() {}

func (x *Query_Insert_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Insert_Res.ProtoReflect.Descriptor instead.
func (*Query_Insert_Res) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 6, 1}
}

func (x *Query_Insert_Res) GetAnswers() []*ConceptMap {
	if x != nil {
		return x.Answers
	}
	return nil
}

type Query_Delete_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *Query_Delete_Req) Reset() {
	*x = Query_Delete_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Delete_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Delete_Req) ProtoMessage() {}

func (x *Query_Delete_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Delete_Req.ProtoReflect.Descriptor instead.
func (*Query_Delete_Req) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 7, 0}
}

func (x *Query_Delete_Req) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type Query_Delete_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Query_Delete_Res) Reset() {
	*x = Query_Delete_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Delete_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Delete_Res) ProtoMessage() {}

func (x *Query_Delete_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Delete_Res.ProtoReflect.Descriptor instead.
func (*Query_Delete_Res) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 7, 1}
}

type Query_Update_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *Query_Update_Req) Reset() {
	*x = Query_Update_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Update_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Update_Req) ProtoMessage() {}

func (x *Query_Update_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Update_Req.ProtoReflect.Descriptor instead.
func (*Query_Update_Req) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 8, 0}
}

func (x *Query_Update_Req) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type Query_Update_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answers []*ConceptMap `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
}

func (x *Query_Update_Res) Reset() {
	*x = Query_Update_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Update_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Update_Res) ProtoMessage() {}

func (x *Query_Update_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Update_Res.ProtoReflect.Descriptor instead.
func (*Query_Update_Res) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 8, 1}
}

func (x *Query_Update_Res) GetAnswers() []*ConceptMap {
	if x != nil {
		return x.Answers
	}
	return nil
}

type Query_Define_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *Query_Define_Req) Reset() {
	*x = Query_Define_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Define_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Define_Req) ProtoMessage() {}

func (x *Query_Define_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Define_Req.ProtoReflect.Descriptor instead.
func (*Query_Define_Req) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 9, 0}
}

func (x *Query_Define_Req) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type Query_Define_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Query_Define_Res) Reset() {
	*x = Query_Define_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Define_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Define_Res) ProtoMessage() {}

func (x *Query_Define_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Define_Res.ProtoReflect.Descriptor instead.
func (*Query_Define_Res) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 9, 1}
}

type Query_Undefine_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *Query_Undefine_Req) Reset() {
	*x = Query_Undefine_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Undefine_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Undefine_Req) ProtoMessage() {}

func (x *Query_Undefine_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Undefine_Req.ProtoReflect.Descriptor instead.
func (*Query_Undefine_Req) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 10, 0}
}

func (x *Query_Undefine_Req) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type Query_Undefine_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Query_Undefine_Res) Reset() {
	*x = Query_Undefine_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_protobuf_query_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Undefine_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Undefine_Res) ProtoMessage() {}

func (x *Query_Undefine_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v2_protobuf_query_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Undefine_Res.ProtoReflect.Descriptor instead.
func (*Query_Undefine_Res) Descriptor() ([]byte, []int) {
	return file_v2_protobuf_query_proto_rawDescGZIP(), []int{0, 10, 1}
}

var File_v2_protobuf_query_proto protoreflect.FileDescriptor

var file_v2_protobuf_query_proto_rawDesc = []byte{
	0x0a, 0x17, 0x76, 0x32, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x67, 0x72, 0x61, 0x6b, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a, 0x18, 0x76, 0x32, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x76, 0x32, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb0,
	0x11, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x1a, 0xec, 0x05, 0x0a, 0x03, 0x52, 0x65, 0x71,
	0x12, 0x31, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x41, 0x0a, 0x0a, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x65,
	0x71, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x44,
	0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x09, 0x64, 0x65, 0x66,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x12, 0x47, 0x0a, 0x0c, 0x75, 0x6e, 0x64, 0x65, 0x66, 0x69,
	0x6e, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x65, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x67,
	0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x2e, 0x55, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x52, 0x65, 0x71,
	0x48, 0x00, 0x52, 0x0b, 0x75, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x3e, 0x0a, 0x09, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x66, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x2e,
	0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12,
	0x5a, 0x0a, 0x13, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61,
	0x74, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x67, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x67,
	0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61,
	0x74, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x11, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x41,
	0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x4e, 0x0a, 0x0f, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x68,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x0d, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x12, 0x6a, 0x0a, 0x19, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x61, 0x67, 0x67, 0x72, 0x65,
	0x67, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x69, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d,
	0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52,
	0x16, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x67, 0x67, 0x72, 0x65,
	0x67, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x41, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x6a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x72,
	0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52,
	0x09, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x41, 0x0a, 0x0a, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x6b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x71,
	0x48, 0x00, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x41, 0x0a,
	0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x6c, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2e,
	0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x42, 0x05, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x1a, 0xb9, 0x05, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x12,
	0x41, 0x0a, 0x0a, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x64, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x44, 0x65, 0x66, 0x69, 0x6e,
	0x65, 0x2e, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x09, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x52,
	0x65, 0x73, 0x12, 0x47, 0x0a, 0x0c, 0x75, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x5f, 0x72,
	0x65, 0x73, 0x18, 0x65, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x2e,
	0x55, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0b,
	0x75, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x09, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x66, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x52, 0x65, 0x73, 0x48,
	0x00, 0x52, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x12, 0x5a, 0x0a, 0x13, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x5f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x5f, 0x72,
	0x65, 0x73, 0x18, 0x67, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x2e,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x52,
	0x65, 0x73, 0x48, 0x00, 0x52, 0x11, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x41, 0x67, 0x67, 0x72, 0x65,
	0x67, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x4e, 0x0a, 0x0f, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x68, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x2e, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0d, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x12, 0x6a, 0x0a, 0x19, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65,
	0x5f, 0x72, 0x65, 0x73, 0x18, 0x69, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x67, 0x72, 0x61,
	0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x67, 0x67, 0x72,
	0x65, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x16, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x12, 0x41, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x5f, 0x72, 0x65,
	0x73, 0x18, 0x6a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x49,
	0x6e, 0x73, 0x65, 0x72, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x09, 0x69, 0x6e, 0x73,
	0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x12, 0x41, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x5f, 0x72, 0x65, 0x73, 0x18, 0x6b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x72, 0x61,
	0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x09,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x41, 0x0a, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x6c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x48,
	0x00, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x42, 0x05, 0x0a, 0x03,
	0x72, 0x65, 0x73, 0x1a, 0x61, 0x0a, 0x05, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x1a, 0x1b, 0x0a, 0x03,
	0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x3b, 0x0a, 0x03, 0x52, 0x65, 0x73,
	0x12, 0x34, 0x0a, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x4d, 0x61, 0x70, 0x52, 0x07, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x1a, 0x65, 0x0a, 0x0e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x41,
	0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x1a, 0x1b, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12,
	0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x36, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x06,
	0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67,
	0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4e, 0x75,
	0x6d, 0x65, 0x72, 0x69, 0x63, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x1a, 0x6b, 0x0a,
	0x0a, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x1a, 0x1b, 0x0a, 0x03, 0x52,
	0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x40, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x12,
	0x39, 0x0a, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x4d, 0x61, 0x70, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x1a, 0x71, 0x0a, 0x13, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74,
	0x65, 0x1a, 0x1b, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x3d,
	0x0a, 0x03, 0x52, 0x65, 0x73, 0x12, 0x36, 0x0a, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x1a, 0x62, 0x0a,
	0x06, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x1a, 0x1b, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x14,
	0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x1a, 0x3b, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x07, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x6f,
	0x6e, 0x63, 0x65, 0x70, 0x74, 0x4d, 0x61, 0x70, 0x52, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x73, 0x1a, 0x2c, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x1a, 0x1b, 0x0a, 0x03, 0x52,
	0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x05, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x1a,
	0x62, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x1a, 0x1b, 0x0a, 0x03, 0x52, 0x65, 0x71,
	0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x3b, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x12, 0x34, 0x0a,
	0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x43, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x4d, 0x61, 0x70, 0x52, 0x07, 0x61, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x73, 0x1a, 0x2c, 0x0a, 0x06, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x1a, 0x1b, 0x0a,
	0x03, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x05, 0x0a, 0x03, 0x52, 0x65,
	0x73, 0x1a, 0x2e, 0x0a, 0x08, 0x55, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x1a, 0x1b, 0x0a,
	0x03, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x05, 0x0a, 0x03, 0x52, 0x65,
	0x73, 0x42, 0x40, 0x0a, 0x0e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x42, 0x0a, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a,
	0x22, 0x2e, 0x2f, 0x76, 0x32, 0x2f, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x3b, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v2_protobuf_query_proto_rawDescOnce sync.Once
	file_v2_protobuf_query_proto_rawDescData = file_v2_protobuf_query_proto_rawDesc
)

func file_v2_protobuf_query_proto_rawDescGZIP() []byte {
	file_v2_protobuf_query_proto_rawDescOnce.Do(func() {
		file_v2_protobuf_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_v2_protobuf_query_proto_rawDescData)
	})
	return file_v2_protobuf_query_proto_rawDescData
}

var file_v2_protobuf_query_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_v2_protobuf_query_proto_goTypes = []interface{}{
	(*Query)(nil),                         // 0: grakn.protocol.Query
	(*Query_Req)(nil),                     // 1: grakn.protocol.Query.Req
	(*Query_Res)(nil),                     // 2: grakn.protocol.Query.Res
	(*Query_Match)(nil),                   // 3: grakn.protocol.Query.Match
	(*Query_MatchAggregate)(nil),          // 4: grakn.protocol.Query.MatchAggregate
	(*Query_MatchGroup)(nil),              // 5: grakn.protocol.Query.MatchGroup
	(*Query_MatchGroupAggregate)(nil),     // 6: grakn.protocol.Query.MatchGroupAggregate
	(*Query_Insert)(nil),                  // 7: grakn.protocol.Query.Insert
	(*Query_Delete)(nil),                  // 8: grakn.protocol.Query.Delete
	(*Query_Update)(nil),                  // 9: grakn.protocol.Query.Update
	(*Query_Define)(nil),                  // 10: grakn.protocol.Query.Define
	(*Query_Undefine)(nil),                // 11: grakn.protocol.Query.Undefine
	(*Query_Match_Req)(nil),               // 12: grakn.protocol.Query.Match.Req
	(*Query_Match_Res)(nil),               // 13: grakn.protocol.Query.Match.Res
	(*Query_MatchAggregate_Req)(nil),      // 14: grakn.protocol.Query.MatchAggregate.Req
	(*Query_MatchAggregate_Res)(nil),      // 15: grakn.protocol.Query.MatchAggregate.Res
	(*Query_MatchGroup_Req)(nil),          // 16: grakn.protocol.Query.MatchGroup.Req
	(*Query_MatchGroup_Res)(nil),          // 17: grakn.protocol.Query.MatchGroup.Res
	(*Query_MatchGroupAggregate_Req)(nil), // 18: grakn.protocol.Query.MatchGroupAggregate.Req
	(*Query_MatchGroupAggregate_Res)(nil), // 19: grakn.protocol.Query.MatchGroupAggregate.Res
	(*Query_Insert_Req)(nil),              // 20: grakn.protocol.Query.Insert.Req
	(*Query_Insert_Res)(nil),              // 21: grakn.protocol.Query.Insert.Res
	(*Query_Delete_Req)(nil),              // 22: grakn.protocol.Query.Delete.Req
	(*Query_Delete_Res)(nil),              // 23: grakn.protocol.Query.Delete.Res
	(*Query_Update_Req)(nil),              // 24: grakn.protocol.Query.Update.Req
	(*Query_Update_Res)(nil),              // 25: grakn.protocol.Query.Update.Res
	(*Query_Define_Req)(nil),              // 26: grakn.protocol.Query.Define.Req
	(*Query_Define_Res)(nil),              // 27: grakn.protocol.Query.Define.Res
	(*Query_Undefine_Req)(nil),            // 28: grakn.protocol.Query.Undefine.Req
	(*Query_Undefine_Res)(nil),            // 29: grakn.protocol.Query.Undefine.Res
	(*Options)(nil),                       // 30: grakn.protocol.Options
	(*ConceptMap)(nil),                    // 31: grakn.protocol.ConceptMap
	(*Numeric)(nil),                       // 32: grakn.protocol.Numeric
	(*ConceptMapGroup)(nil),               // 33: grakn.protocol.ConceptMapGroup
	(*NumericGroup)(nil),                  // 34: grakn.protocol.NumericGroup
}
var file_v2_protobuf_query_proto_depIdxs = []int32{
	30, // 0: grakn.protocol.Query.Req.options:type_name -> grakn.protocol.Options
	26, // 1: grakn.protocol.Query.Req.define_req:type_name -> grakn.protocol.Query.Define.Req
	28, // 2: grakn.protocol.Query.Req.undefine_req:type_name -> grakn.protocol.Query.Undefine.Req
	12, // 3: grakn.protocol.Query.Req.match_req:type_name -> grakn.protocol.Query.Match.Req
	14, // 4: grakn.protocol.Query.Req.match_aggregate_req:type_name -> grakn.protocol.Query.MatchAggregate.Req
	16, // 5: grakn.protocol.Query.Req.match_group_req:type_name -> grakn.protocol.Query.MatchGroup.Req
	18, // 6: grakn.protocol.Query.Req.match_group_aggregate_req:type_name -> grakn.protocol.Query.MatchGroupAggregate.Req
	20, // 7: grakn.protocol.Query.Req.insert_req:type_name -> grakn.protocol.Query.Insert.Req
	22, // 8: grakn.protocol.Query.Req.delete_req:type_name -> grakn.protocol.Query.Delete.Req
	24, // 9: grakn.protocol.Query.Req.update_req:type_name -> grakn.protocol.Query.Update.Req
	27, // 10: grakn.protocol.Query.Res.define_res:type_name -> grakn.protocol.Query.Define.Res
	29, // 11: grakn.protocol.Query.Res.undefine_res:type_name -> grakn.protocol.Query.Undefine.Res
	13, // 12: grakn.protocol.Query.Res.match_res:type_name -> grakn.protocol.Query.Match.Res
	15, // 13: grakn.protocol.Query.Res.match_aggregate_res:type_name -> grakn.protocol.Query.MatchAggregate.Res
	17, // 14: grakn.protocol.Query.Res.match_group_res:type_name -> grakn.protocol.Query.MatchGroup.Res
	19, // 15: grakn.protocol.Query.Res.match_group_aggregate_res:type_name -> grakn.protocol.Query.MatchGroupAggregate.Res
	21, // 16: grakn.protocol.Query.Res.insert_res:type_name -> grakn.protocol.Query.Insert.Res
	23, // 17: grakn.protocol.Query.Res.delete_res:type_name -> grakn.protocol.Query.Delete.Res
	25, // 18: grakn.protocol.Query.Res.update_res:type_name -> grakn.protocol.Query.Update.Res
	31, // 19: grakn.protocol.Query.Match.Res.answers:type_name -> grakn.protocol.ConceptMap
	32, // 20: grakn.protocol.Query.MatchAggregate.Res.answer:type_name -> grakn.protocol.Numeric
	33, // 21: grakn.protocol.Query.MatchGroup.Res.answers:type_name -> grakn.protocol.ConceptMapGroup
	34, // 22: grakn.protocol.Query.MatchGroupAggregate.Res.answers:type_name -> grakn.protocol.NumericGroup
	31, // 23: grakn.protocol.Query.Insert.Res.answers:type_name -> grakn.protocol.ConceptMap
	31, // 24: grakn.protocol.Query.Update.Res.answers:type_name -> grakn.protocol.ConceptMap
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_v2_protobuf_query_proto_init() }
func file_v2_protobuf_query_proto_init() {
	if File_v2_protobuf_query_proto != nil {
		return
	}
	file_v2_protobuf_answer_proto_init()
	file_v2_protobuf_options_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_v2_protobuf_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Match); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_MatchAggregate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_MatchGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_MatchGroupAggregate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Insert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Delete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Define); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Undefine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Match_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Match_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_MatchAggregate_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_MatchAggregate_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_MatchGroup_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_MatchGroup_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_MatchGroupAggregate_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_MatchGroupAggregate_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Insert_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Insert_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Delete_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Delete_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Update_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Update_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Define_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Define_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Undefine_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_protobuf_query_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Undefine_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v2_protobuf_query_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Query_Req_DefineReq)(nil),
		(*Query_Req_UndefineReq)(nil),
		(*Query_Req_MatchReq)(nil),
		(*Query_Req_MatchAggregateReq)(nil),
		(*Query_Req_MatchGroupReq)(nil),
		(*Query_Req_MatchGroupAggregateReq)(nil),
		(*Query_Req_InsertReq)(nil),
		(*Query_Req_DeleteReq)(nil),
		(*Query_Req_UpdateReq)(nil),
	}
	file_v2_protobuf_query_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Query_Res_DefineRes)(nil),
		(*Query_Res_UndefineRes)(nil),
		(*Query_Res_MatchRes)(nil),
		(*Query_Res_MatchAggregateRes)(nil),
		(*Query_Res_MatchGroupRes)(nil),
		(*Query_Res_MatchGroupAggregateRes)(nil),
		(*Query_Res_InsertRes)(nil),
		(*Query_Res_DeleteRes)(nil),
		(*Query_Res_UpdateRes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v2_protobuf_query_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_protobuf_query_proto_goTypes,
		DependencyIndexes: file_v2_protobuf_query_proto_depIdxs,
		MessageInfos:      file_v2_protobuf_query_proto_msgTypes,
	}.Build()
	File_v2_protobuf_query_proto = out.File
	file_v2_protobuf_query_proto_rawDesc = nil
	file_v2_protobuf_query_proto_goTypes = nil
	file_v2_protobuf_query_proto_depIdxs = nil
}
