//
// Copyright (C) 2020 Grakn Labs
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: protobuf/query.proto

package grakn_protocol

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Query struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Query) Reset() {
	*x = Query{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_v2_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_v2_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_protobuf_v2_query_proto_rawDescGZIP(), []int{0}
}

type Graql struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Graql) Reset() {
	*x = Graql{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_v2_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Graql) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graql) ProtoMessage() {}

func (x *Graql) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_v2_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graql.ProtoReflect.Descriptor instead.
func (*Graql) Descriptor() ([]byte, []int) {
	return file_protobuf_v2_query_proto_rawDescGZIP(), []int{1}
}

type Query_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options *Options `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	// Types that are assignable to Req:
	//	*Query_Req_DeleteReq
	//	*Query_Req_DefineReq
	//	*Query_Req_UndefineReq
	//	*Query_Req_MatchReq
	//	*Query_Req_InsertReq
	Req isQuery_Req_Req `protobuf_oneof:"req"`
}

func (x *Query_Req) Reset() {
	*x = Query_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_v2_query_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Req) ProtoMessage() {}

func (x *Query_Req) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_v2_query_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Req.ProtoReflect.Descriptor instead.
func (*Query_Req) Descriptor() ([]byte, []int) {
	return file_protobuf_v2_query_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Query_Req) GetOptions() *Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (m *Query_Req) GetReq() isQuery_Req_Req {
	if m != nil {
		return m.Req
	}
	return nil
}

func (x *Query_Req) GetDeleteReq() *Graql_Delete_Req {
	if x, ok := x.GetReq().(*Query_Req_DeleteReq); ok {
		return x.DeleteReq
	}
	return nil
}

func (x *Query_Req) GetDefineReq() *Graql_Define_Req {
	if x, ok := x.GetReq().(*Query_Req_DefineReq); ok {
		return x.DefineReq
	}
	return nil
}

func (x *Query_Req) GetUndefineReq() *Graql_Undefine_Req {
	if x, ok := x.GetReq().(*Query_Req_UndefineReq); ok {
		return x.UndefineReq
	}
	return nil
}

func (x *Query_Req) GetMatchReq() *Graql_Match_Req {
	if x, ok := x.GetReq().(*Query_Req_MatchReq); ok {
		return x.MatchReq
	}
	return nil
}

func (x *Query_Req) GetInsertReq() *Graql_Insert_Req {
	if x, ok := x.GetReq().(*Query_Req_InsertReq); ok {
		return x.InsertReq
	}
	return nil
}

type isQuery_Req_Req interface {
	isQuery_Req_Req()
}

type Query_Req_DeleteReq struct {
	DeleteReq *Graql_Delete_Req `protobuf:"bytes,100,opt,name=delete_req,json=deleteReq,proto3,oneof"`
}

type Query_Req_DefineReq struct {
	DefineReq *Graql_Define_Req `protobuf:"bytes,101,opt,name=define_req,json=defineReq,proto3,oneof"`
}

type Query_Req_UndefineReq struct {
	UndefineReq *Graql_Undefine_Req `protobuf:"bytes,102,opt,name=undefine_req,json=undefineReq,proto3,oneof"`
}

type Query_Req_MatchReq struct {
	MatchReq *Graql_Match_Req `protobuf:"bytes,103,opt,name=match_req,json=matchReq,proto3,oneof"`
}

type Query_Req_InsertReq struct {
	InsertReq *Graql_Insert_Req `protobuf:"bytes,104,opt,name=insert_req,json=insertReq,proto3,oneof"`
}

func (*Query_Req_DeleteReq) isQuery_Req_Req() {}

func (*Query_Req_DefineReq) isQuery_Req_Req() {}

func (*Query_Req_UndefineReq) isQuery_Req_Req() {}

func (*Query_Req_MatchReq) isQuery_Req_Req() {}

func (*Query_Req_InsertReq) isQuery_Req_Req() {}

type Query_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Res:
	//	*Query_Res_DeleteRes
	//	*Query_Res_DefineRes
	//	*Query_Res_UndefineRes
	//	*Query_Res_MatchRes
	//	*Query_Res_InsertRes
	Res isQuery_Res_Res `protobuf_oneof:"res"`
}

func (x *Query_Res) Reset() {
	*x = Query_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_v2_query_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Res) ProtoMessage() {}

func (x *Query_Res) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_v2_query_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Res.ProtoReflect.Descriptor instead.
func (*Query_Res) Descriptor() ([]byte, []int) {
	return file_protobuf_v2_query_proto_rawDescGZIP(), []int{0, 1}
}

func (m *Query_Res) GetRes() isQuery_Res_Res {
	if m != nil {
		return m.Res
	}
	return nil
}

func (x *Query_Res) GetDeleteRes() *Graql_Delete_Res {
	if x, ok := x.GetRes().(*Query_Res_DeleteRes); ok {
		return x.DeleteRes
	}
	return nil
}

func (x *Query_Res) GetDefineRes() *Graql_Define_Res {
	if x, ok := x.GetRes().(*Query_Res_DefineRes); ok {
		return x.DefineRes
	}
	return nil
}

func (x *Query_Res) GetUndefineRes() *Graql_Undefine_Res {
	if x, ok := x.GetRes().(*Query_Res_UndefineRes); ok {
		return x.UndefineRes
	}
	return nil
}

func (x *Query_Res) GetMatchRes() *Graql_Match_Res {
	if x, ok := x.GetRes().(*Query_Res_MatchRes); ok {
		return x.MatchRes
	}
	return nil
}

func (x *Query_Res) GetInsertRes() *Graql_Insert_Res {
	if x, ok := x.GetRes().(*Query_Res_InsertRes); ok {
		return x.InsertRes
	}
	return nil
}

type isQuery_Res_Res interface {
	isQuery_Res_Res()
}

type Query_Res_DeleteRes struct {
	DeleteRes *Graql_Delete_Res `protobuf:"bytes,100,opt,name=delete_res,json=deleteRes,proto3,oneof"`
}

type Query_Res_DefineRes struct {
	DefineRes *Graql_Define_Res `protobuf:"bytes,101,opt,name=define_res,json=defineRes,proto3,oneof"`
}

type Query_Res_UndefineRes struct {
	UndefineRes *Graql_Undefine_Res `protobuf:"bytes,102,opt,name=undefine_res,json=undefineRes,proto3,oneof"`
}

type Query_Res_MatchRes struct {
	MatchRes *Graql_Match_Res `protobuf:"bytes,103,opt,name=match_res,json=matchRes,proto3,oneof"`
}

type Query_Res_InsertRes struct {
	InsertRes *Graql_Insert_Res `protobuf:"bytes,104,opt,name=insert_res,json=insertRes,proto3,oneof"`
}

func (*Query_Res_DeleteRes) isQuery_Res_Res() {}

func (*Query_Res_DefineRes) isQuery_Res_Res() {}

func (*Query_Res_UndefineRes) isQuery_Res_Res() {}

func (*Query_Res_MatchRes) isQuery_Res_Res() {}

func (*Query_Res_InsertRes) isQuery_Res_Res() {}

type Graql_Match struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Graql_Match) Reset() {
	*x = Graql_Match{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_v2_query_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Graql_Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graql_Match) ProtoMessage() {}

func (x *Graql_Match) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_v2_query_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graql_Match.ProtoReflect.Descriptor instead.
func (*Graql_Match) Descriptor() ([]byte, []int) {
	return file_protobuf_v2_query_proto_rawDescGZIP(), []int{1, 0}
}

type Graql_Insert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Graql_Insert) Reset() {
	*x = Graql_Insert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_v2_query_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Graql_Insert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graql_Insert) ProtoMessage() {}

func (x *Graql_Insert) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_v2_query_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graql_Insert.ProtoReflect.Descriptor instead.
func (*Graql_Insert) Descriptor() ([]byte, []int) {
	return file_protobuf_v2_query_proto_rawDescGZIP(), []int{1, 1}
}

type Graql_Delete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Graql_Delete) Reset() {
	*x = Graql_Delete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_v2_query_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Graql_Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graql_Delete) ProtoMessage() {}

func (x *Graql_Delete) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_v2_query_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graql_Delete.ProtoReflect.Descriptor instead.
func (*Graql_Delete) Descriptor() ([]byte, []int) {
	return file_protobuf_v2_query_proto_rawDescGZIP(), []int{1, 2}
}

type Graql_Define struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Graql_Define) Reset() {
	*x = Graql_Define{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_v2_query_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Graql_Define) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graql_Define) ProtoMessage() {}

func (x *Graql_Define) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_v2_query_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graql_Define.ProtoReflect.Descriptor instead.
func (*Graql_Define) Descriptor() ([]byte, []int) {
	return file_protobuf_v2_query_proto_rawDescGZIP(), []int{1, 3}
}

type Graql_Undefine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Graql_Undefine) Reset() {
	*x = Graql_Undefine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_v2_query_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Graql_Undefine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graql_Undefine) ProtoMessage() {}

func (x *Graql_Undefine) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_v2_query_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graql_Undefine.ProtoReflect.Descriptor instead.
func (*Graql_Undefine) Descriptor() ([]byte, []int) {
	return file_protobuf_v2_query_proto_rawDescGZIP(), []int{1, 4}
}

type Graql_Match_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *Graql_Match_Req) Reset() {
	*x = Graql_Match_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_v2_query_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Graql_Match_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graql_Match_Req) ProtoMessage() {}

func (x *Graql_Match_Req) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_v2_query_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graql_Match_Req.ProtoReflect.Descriptor instead.
func (*Graql_Match_Req) Descriptor() ([]byte, []int) {
	return file_protobuf_v2_query_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *Graql_Match_Req) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// @Iterable
type Graql_Match_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer *ConceptMap `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *Graql_Match_Res) Reset() {
	*x = Graql_Match_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_v2_query_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Graql_Match_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graql_Match_Res) ProtoMessage() {}

func (x *Graql_Match_Res) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_v2_query_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graql_Match_Res.ProtoReflect.Descriptor instead.
func (*Graql_Match_Res) Descriptor() ([]byte, []int) {
	return file_protobuf_v2_query_proto_rawDescGZIP(), []int{1, 0, 1}
}

func (x *Graql_Match_Res) GetAnswer() *ConceptMap {
	if x != nil {
		return x.Answer
	}
	return nil
}

type Graql_Insert_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *Graql_Insert_Req) Reset() {
	*x = Graql_Insert_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_v2_query_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Graql_Insert_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graql_Insert_Req) ProtoMessage() {}

func (x *Graql_Insert_Req) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_v2_query_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graql_Insert_Req.ProtoReflect.Descriptor instead.
func (*Graql_Insert_Req) Descriptor() ([]byte, []int) {
	return file_protobuf_v2_query_proto_rawDescGZIP(), []int{1, 1, 0}
}

func (x *Graql_Insert_Req) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// @Iterable
type Graql_Insert_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer *ConceptMap `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *Graql_Insert_Res) Reset() {
	*x = Graql_Insert_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_v2_query_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Graql_Insert_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graql_Insert_Res) ProtoMessage() {}

func (x *Graql_Insert_Res) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_v2_query_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graql_Insert_Res.ProtoReflect.Descriptor instead.
func (*Graql_Insert_Res) Descriptor() ([]byte, []int) {
	return file_protobuf_v2_query_proto_rawDescGZIP(), []int{1, 1, 1}
}

func (x *Graql_Insert_Res) GetAnswer() *ConceptMap {
	if x != nil {
		return x.Answer
	}
	return nil
}

type Graql_Delete_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *Graql_Delete_Req) Reset() {
	*x = Graql_Delete_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_v2_query_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Graql_Delete_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graql_Delete_Req) ProtoMessage() {}

func (x *Graql_Delete_Req) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_v2_query_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graql_Delete_Req.ProtoReflect.Descriptor instead.
func (*Graql_Delete_Req) Descriptor() ([]byte, []int) {
	return file_protobuf_v2_query_proto_rawDescGZIP(), []int{1, 2, 0}
}

func (x *Graql_Delete_Req) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type Graql_Delete_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Graql_Delete_Res) Reset() {
	*x = Graql_Delete_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_v2_query_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Graql_Delete_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graql_Delete_Res) ProtoMessage() {}

func (x *Graql_Delete_Res) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_v2_query_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graql_Delete_Res.ProtoReflect.Descriptor instead.
func (*Graql_Delete_Res) Descriptor() ([]byte, []int) {
	return file_protobuf_v2_query_proto_rawDescGZIP(), []int{1, 2, 1}
}

type Graql_Define_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *Graql_Define_Req) Reset() {
	*x = Graql_Define_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_v2_query_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Graql_Define_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graql_Define_Req) ProtoMessage() {}

func (x *Graql_Define_Req) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_v2_query_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graql_Define_Req.ProtoReflect.Descriptor instead.
func (*Graql_Define_Req) Descriptor() ([]byte, []int) {
	return file_protobuf_v2_query_proto_rawDescGZIP(), []int{1, 3, 0}
}

func (x *Graql_Define_Req) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type Graql_Define_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Graql_Define_Res) Reset() {
	*x = Graql_Define_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_v2_query_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Graql_Define_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graql_Define_Res) ProtoMessage() {}

func (x *Graql_Define_Res) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_v2_query_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graql_Define_Res.ProtoReflect.Descriptor instead.
func (*Graql_Define_Res) Descriptor() ([]byte, []int) {
	return file_protobuf_v2_query_proto_rawDescGZIP(), []int{1, 3, 1}
}

type Graql_Undefine_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *Graql_Undefine_Req) Reset() {
	*x = Graql_Undefine_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_v2_query_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Graql_Undefine_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graql_Undefine_Req) ProtoMessage() {}

func (x *Graql_Undefine_Req) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_v2_query_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graql_Undefine_Req.ProtoReflect.Descriptor instead.
func (*Graql_Undefine_Req) Descriptor() ([]byte, []int) {
	return file_protobuf_v2_query_proto_rawDescGZIP(), []int{1, 4, 0}
}

func (x *Graql_Undefine_Req) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type Graql_Undefine_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Graql_Undefine_Res) Reset() {
	*x = Graql_Undefine_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_v2_query_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Graql_Undefine_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graql_Undefine_Res) ProtoMessage() {}

func (x *Graql_Undefine_Res) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_v2_query_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graql_Undefine_Res.ProtoReflect.Descriptor instead.
func (*Graql_Undefine_Res) Descriptor() ([]byte, []int) {
	return file_protobuf_v2_query_proto_rawDescGZIP(), []int{1, 4, 1}
}

var File_protobuf_v2_query_proto protoreflect.FileDescriptor

var file_protobuf_v2_query_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x76, 0x32, 0x2f, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x67, 0x72, 0x61, 0x6b, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x5f, 0x76, 0x32, 0x2f, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x76, 0x32,
	0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfc,
	0x05, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x91, 0x03, 0x0a, 0x03, 0x52, 0x65, 0x71,
	0x12, 0x31, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x41, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x72, 0x65,
	0x71, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x47, 0x72, 0x61, 0x71, 0x6c, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x09, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x41, 0x0a, 0x0a, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65,
	0x5f, 0x72, 0x65, 0x71, 0x18, 0x65, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x72, 0x61,
	0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x47, 0x72, 0x61, 0x71,
	0x6c, 0x2e, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x09,
	0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x12, 0x47, 0x0a, 0x0c, 0x75, 0x6e, 0x64,
	0x65, 0x66, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x66, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x47, 0x72, 0x61, 0x71, 0x6c, 0x2e, 0x55, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e,
	0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x0b, 0x75, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x3e, 0x0a, 0x09, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x72, 0x65, 0x71, 0x18,
	0x67, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x47, 0x72, 0x61, 0x71, 0x6c, 0x2e, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x2e, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x71, 0x12, 0x41, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x5f, 0x72, 0x65, 0x71,
	0x18, 0x68, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x47, 0x72, 0x61, 0x71, 0x6c, 0x2e, 0x49, 0x6e,
	0x73, 0x65, 0x72, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x09, 0x69, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x42, 0x05, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x1a, 0xde, 0x02, 0x0a,
	0x03, 0x52, 0x65, 0x73, 0x12, 0x41, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x72,
	0x65, 0x73, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x47, 0x72, 0x61, 0x71, 0x6c, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x09, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x41, 0x0a, 0x0a, 0x64, 0x65, 0x66, 0x69, 0x6e,
	0x65, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x65, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x72,
	0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x47, 0x72, 0x61,
	0x71, 0x6c, 0x2e, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52,
	0x09, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x12, 0x47, 0x0a, 0x0c, 0x75, 0x6e,
	0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x66, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x47, 0x72, 0x61, 0x71, 0x6c, 0x2e, 0x55, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65,
	0x2e, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0b, 0x75, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65,
	0x52, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x09, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x72, 0x65, 0x73,
	0x18, 0x67, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x47, 0x72, 0x61, 0x71, 0x6c, 0x2e, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x2e, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x73, 0x12, 0x41, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x5f, 0x72, 0x65,
	0x73, 0x18, 0x68, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x47, 0x72, 0x61, 0x71, 0x6c, 0x2e, 0x49,
	0x6e, 0x73, 0x65, 0x72, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x09, 0x69, 0x6e, 0x73,
	0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x42, 0x05, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x22, 0xd6, 0x02,
	0x0a, 0x05, 0x47, 0x72, 0x61, 0x71, 0x6c, 0x1a, 0x5f, 0x0a, 0x05, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x1a, 0x1b, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x39, 0x0a,
	0x03, 0x52, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x4d, 0x61, 0x70,
	0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x1a, 0x60, 0x0a, 0x06, 0x49, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x1a, 0x1b, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x1a,
	0x39, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x4d,
	0x61, 0x70, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x1a, 0x2c, 0x0a, 0x06, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x1a, 0x1b, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x1a, 0x05, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x1a, 0x2c, 0x0a, 0x06, 0x44, 0x65, 0x66, 0x69,
	0x6e, 0x65, 0x1a, 0x1b, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x1a,
	0x05, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x1a, 0x2e, 0x0a, 0x08, 0x55, 0x6e, 0x64, 0x65, 0x66, 0x69,
	0x6e, 0x65, 0x1a, 0x1b, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x1a,
	0x05, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x42, 0x43, 0x0a, 0x0e, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x42, 0x0a, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x25, 0x2e, 0x2f, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x76, 0x32, 0x3b, 0x67, 0x72, 0x61, 0x6b, 0x6e, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protobuf_v2_query_proto_rawDescOnce sync.Once
	file_protobuf_v2_query_proto_rawDescData = file_protobuf_v2_query_proto_rawDesc
)

func file_protobuf_v2_query_proto_rawDescGZIP() []byte {
	file_protobuf_v2_query_proto_rawDescOnce.Do(func() {
		file_protobuf_v2_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_v2_query_proto_rawDescData)
	})
	return file_protobuf_v2_query_proto_rawDescData
}

var file_protobuf_v2_query_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_protobuf_v2_query_proto_goTypes = []interface{}{
	(*Query)(nil),              // 0: grakn.protocol.Query
	(*Graql)(nil),              // 1: grakn.protocol.Graql
	(*Query_Req)(nil),          // 2: grakn.protocol.Query.Req
	(*Query_Res)(nil),          // 3: grakn.protocol.Query.Res
	(*Graql_Match)(nil),        // 4: grakn.protocol.Graql.Match
	(*Graql_Insert)(nil),       // 5: grakn.protocol.Graql.Insert
	(*Graql_Delete)(nil),       // 6: grakn.protocol.Graql.Delete
	(*Graql_Define)(nil),       // 7: grakn.protocol.Graql.Define
	(*Graql_Undefine)(nil),     // 8: grakn.protocol.Graql.Undefine
	(*Graql_Match_Req)(nil),    // 9: grakn.protocol.Graql.Match.Req
	(*Graql_Match_Res)(nil),    // 10: grakn.protocol.Graql.Match.Res
	(*Graql_Insert_Req)(nil),   // 11: grakn.protocol.Graql.Insert.Req
	(*Graql_Insert_Res)(nil),   // 12: grakn.protocol.Graql.Insert.Res
	(*Graql_Delete_Req)(nil),   // 13: grakn.protocol.Graql.Delete.Req
	(*Graql_Delete_Res)(nil),   // 14: grakn.protocol.Graql.Delete.Res
	(*Graql_Define_Req)(nil),   // 15: grakn.protocol.Graql.Define.Req
	(*Graql_Define_Res)(nil),   // 16: grakn.protocol.Graql.Define.Res
	(*Graql_Undefine_Req)(nil), // 17: grakn.protocol.Graql.Undefine.Req
	(*Graql_Undefine_Res)(nil), // 18: grakn.protocol.Graql.Undefine.Res
	(*Options)(nil),            // 19: grakn.protocol.Options
	(*ConceptMap)(nil),         // 20: grakn.protocol.ConceptMap
}
var file_protobuf_v2_query_proto_depIdxs = []int32{
	19, // 0: grakn.protocol.Query.Req.options:type_name -> grakn.protocol.Options
	13, // 1: grakn.protocol.Query.Req.delete_req:type_name -> grakn.protocol.Graql.Delete.Req
	15, // 2: grakn.protocol.Query.Req.define_req:type_name -> grakn.protocol.Graql.Define.Req
	17, // 3: grakn.protocol.Query.Req.undefine_req:type_name -> grakn.protocol.Graql.Undefine.Req
	9,  // 4: grakn.protocol.Query.Req.match_req:type_name -> grakn.protocol.Graql.Match.Req
	11, // 5: grakn.protocol.Query.Req.insert_req:type_name -> grakn.protocol.Graql.Insert.Req
	14, // 6: grakn.protocol.Query.Res.delete_res:type_name -> grakn.protocol.Graql.Delete.Res
	16, // 7: grakn.protocol.Query.Res.define_res:type_name -> grakn.protocol.Graql.Define.Res
	18, // 8: grakn.protocol.Query.Res.undefine_res:type_name -> grakn.protocol.Graql.Undefine.Res
	10, // 9: grakn.protocol.Query.Res.match_res:type_name -> grakn.protocol.Graql.Match.Res
	12, // 10: grakn.protocol.Query.Res.insert_res:type_name -> grakn.protocol.Graql.Insert.Res
	20, // 11: grakn.protocol.Graql.Match.Res.answer:type_name -> grakn.protocol.ConceptMap
	20, // 12: grakn.protocol.Graql.Insert.Res.answer:type_name -> grakn.protocol.ConceptMap
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_protobuf_v2_query_proto_init() }
func file_protobuf_v2_query_proto_init() {
	if File_protobuf_v2_query_proto != nil {
		return
	}
	file_protobuf_v2_answer_proto_init()
	file_protobuf_v2_options_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protobuf_v2_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_v2_query_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Graql); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_v2_query_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_v2_query_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_v2_query_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Graql_Match); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_v2_query_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Graql_Insert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_v2_query_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Graql_Delete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_v2_query_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Graql_Define); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_v2_query_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Graql_Undefine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_v2_query_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Graql_Match_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_v2_query_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Graql_Match_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_v2_query_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Graql_Insert_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_v2_query_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Graql_Insert_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_v2_query_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Graql_Delete_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_v2_query_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Graql_Delete_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_v2_query_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Graql_Define_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_v2_query_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Graql_Define_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_v2_query_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Graql_Undefine_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_v2_query_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Graql_Undefine_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobuf_v2_query_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Query_Req_DeleteReq)(nil),
		(*Query_Req_DefineReq)(nil),
		(*Query_Req_UndefineReq)(nil),
		(*Query_Req_MatchReq)(nil),
		(*Query_Req_InsertReq)(nil),
	}
	file_protobuf_v2_query_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*Query_Res_DeleteRes)(nil),
		(*Query_Res_DefineRes)(nil),
		(*Query_Res_UndefineRes)(nil),
		(*Query_Res_MatchRes)(nil),
		(*Query_Res_InsertRes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_v2_query_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_v2_query_proto_goTypes,
		DependencyIndexes: file_protobuf_v2_query_proto_depIdxs,
		MessageInfos:      file_protobuf_v2_query_proto_msgTypes,
	}.Build()
	File_protobuf_v2_query_proto = out.File
	file_protobuf_v2_query_proto_rawDesc = nil
	file_protobuf_v2_query_proto_goTypes = nil
	file_protobuf_v2_query_proto_depIdxs = nil
}
