// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package typedb_protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// TypeDBClusterClient is the client API for TypeDBCluster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TypeDBClusterClient interface {
	ServersAll(ctx context.Context, in *ServerManager_All_Req, opts ...grpc.CallOption) (*ServerManager_All_Res, error)
	DatabasesGet(ctx context.Context, in *ClusterDatabaseManager_Get_Req, opts ...grpc.CallOption) (*ClusterDatabaseManager_Get_Res, error)
	DatabasesAll(ctx context.Context, in *ClusterDatabaseManager_All_Req, opts ...grpc.CallOption) (*ClusterDatabaseManager_All_Res, error)
}

type typeDBClusterClient struct {
	cc grpc.ClientConnInterface
}

func NewTypeDBClusterClient(cc grpc.ClientConnInterface) TypeDBClusterClient {
	return &typeDBClusterClient{cc}
}

func (c *typeDBClusterClient) ServersAll(ctx context.Context, in *ServerManager_All_Req, opts ...grpc.CallOption) (*ServerManager_All_Res, error) {
	out := new(ServerManager_All_Res)
	err := c.cc.Invoke(ctx, "/typedb.protocol.TypeDBCluster/servers_all", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *typeDBClusterClient) DatabasesGet(ctx context.Context, in *ClusterDatabaseManager_Get_Req, opts ...grpc.CallOption) (*ClusterDatabaseManager_Get_Res, error) {
	out := new(ClusterDatabaseManager_Get_Res)
	err := c.cc.Invoke(ctx, "/typedb.protocol.TypeDBCluster/databases_get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *typeDBClusterClient) DatabasesAll(ctx context.Context, in *ClusterDatabaseManager_All_Req, opts ...grpc.CallOption) (*ClusterDatabaseManager_All_Res, error) {
	out := new(ClusterDatabaseManager_All_Res)
	err := c.cc.Invoke(ctx, "/typedb.protocol.TypeDBCluster/databases_all", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TypeDBClusterServer is the server API for TypeDBCluster service.
// All implementations must embed UnimplementedTypeDBClusterServer
// for forward compatibility
type TypeDBClusterServer interface {
	ServersAll(context.Context, *ServerManager_All_Req) (*ServerManager_All_Res, error)
	DatabasesGet(context.Context, *ClusterDatabaseManager_Get_Req) (*ClusterDatabaseManager_Get_Res, error)
	DatabasesAll(context.Context, *ClusterDatabaseManager_All_Req) (*ClusterDatabaseManager_All_Res, error)
	mustEmbedUnimplementedTypeDBClusterServer()
}

// UnimplementedTypeDBClusterServer must be embedded to have forward compatible implementations.
type UnimplementedTypeDBClusterServer struct {
}

func (UnimplementedTypeDBClusterServer) ServersAll(context.Context, *ServerManager_All_Req) (*ServerManager_All_Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServersAll not implemented")
}
func (UnimplementedTypeDBClusterServer) DatabasesGet(context.Context, *ClusterDatabaseManager_Get_Req) (*ClusterDatabaseManager_Get_Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DatabasesGet not implemented")
}
func (UnimplementedTypeDBClusterServer) DatabasesAll(context.Context, *ClusterDatabaseManager_All_Req) (*ClusterDatabaseManager_All_Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DatabasesAll not implemented")
}
func (UnimplementedTypeDBClusterServer) mustEmbedUnimplementedTypeDBClusterServer() {}

// UnsafeTypeDBClusterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TypeDBClusterServer will
// result in compilation errors.
type UnsafeTypeDBClusterServer interface {
	mustEmbedUnimplementedTypeDBClusterServer()
}

func RegisterTypeDBClusterServer(s grpc.ServiceRegistrar, srv TypeDBClusterServer) {
	s.RegisterService(&_TypeDBCluster_serviceDesc, srv)
}

func _TypeDBCluster_ServersAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerManager_All_Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypeDBClusterServer).ServersAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/typedb.protocol.TypeDBCluster/servers_all",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypeDBClusterServer).ServersAll(ctx, req.(*ServerManager_All_Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _TypeDBCluster_DatabasesGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterDatabaseManager_Get_Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypeDBClusterServer).DatabasesGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/typedb.protocol.TypeDBCluster/databases_get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypeDBClusterServer).DatabasesGet(ctx, req.(*ClusterDatabaseManager_Get_Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _TypeDBCluster_DatabasesAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterDatabaseManager_All_Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypeDBClusterServer).DatabasesAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/typedb.protocol.TypeDBCluster/databases_all",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypeDBClusterServer).DatabasesAll(ctx, req.(*ClusterDatabaseManager_All_Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _TypeDBCluster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "typedb.protocol.TypeDBCluster",
	HandlerType: (*TypeDBClusterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "servers_all",
			Handler:    _TypeDBCluster_ServersAll_Handler,
		},
		{
			MethodName: "databases_get",
			Handler:    _TypeDBCluster_DatabasesGet_Handler,
		},
		{
			MethodName: "databases_all",
			Handler:    _TypeDBCluster_DatabasesAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v2/protobuf/cluster/cluster_service.proto",
}
